[register]
provider = "scb"
slug = "grundskola-prov-ak6"
native_id = "320"

[[enrichment.description]]
register = "scb/grundskola-prov-ak6"
variable = "personnr"
description = "Löpnummer i populationen"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[enrichment.description]]
register = "scb/grundskola-prov-ak6"
variable = "skolenhetskod"
description = "Skolenhetskod (löpnummersätts vid leverans)"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[enrichment.description]]
register = "scb/grundskola-prov-ak6"
variable = "skolkod"
description = "Skolkod (löpnummersätts vid leverans)"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[enrichment.description]]
register = "scb/grundskola-prov-ak6"
variable = "skolkommun"
description = "Skolkommun"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[enrichment.description]]
register = "scb/grundskola-prov-ak6"
variable = "sv-delprov-b"
description = "Resultat på delprov B i svenska"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[enrichment.description]]
register = "scb/grundskola-prov-ak6"
variable = "sv-delprov-c"
description = "Resultat på delprov C i svenska"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[enrichment.description]]
register = "scb/grundskola-prov-ak6"
variable = "sv-eller-sva"
description = "Anger vilken kursplan i svenska eleven följer"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[code_label_pair]]
code = "scb/grundskola-prov-ak6/skolkod"
label = "scb/grundskola-prov-ak6/skolans-namn"
