[register]
provider = "scb"
slug = "hushallens-boende"
native_id = "346"

[[enrichment.description]]
register = "scb/hushallens-boende"
variable = "boarea"
description = "Bostadsarea"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[enrichment.description]]
register = "scb/hushallens-boende"
variable = "scb-upplatform"
description = "Bostadens upplåtelseform"
provenance = "Utkast_P1105_Variabellista_uppd2025_v5.xlsx"

[[variant]]
native_id = "346.1154"
slug = "individer"
display_group = "Individer"
panel_entity_key = "personnr"
panel_time_key = "period"
panel_time_grain = "delivery"

# Historiska befolkningsregistret (HBR)

[[variable]]
native_id = "346.57"
slug = "personnr"


[[variable]]
native_id = "346.15"
slug = "civilstand"

[[variable]]
native_id = "346.26"
slug = "fastighetsbeteckning"

[[variable]]
native_id = "346.241"
slug = "alder-31-12"

[[variable]]
native_id = "346.254"
slug = "folkbokforingsdatum"

[[variable]]
native_id = "346.257"
slug = "fodelseland-rtb"

[[variable]]
native_id = "346.271"
slug = "medborgarskapsland"

[[variable]]
native_id = "346.388"
slug = "antal-barn"

[[variable]]
native_id = "346.389"
slug = "antal-barn-under-18-ar"

[[variable]]
native_id = "346.391"
slug = "antal-barn-under-6-ar"

[[variable]]
native_id = "346.2299"
slug = "lagenhetstyp"

[[variable]]
native_id = "346.3730"
slug = "fastighetens-identitetsnummer"

[[variable]]
native_id = "346.29339"
slug = "hushallstyp-bostadshushall"

[[variable]]
native_id = "346.29828"
slug = "lagenhetsnyckel"

[[variable]]
native_id = "346.29832"
slug = "lopnummer-bostadshushall"

[[variable]]
native_id = "346.30120"
slug = "bostadskategori"

[[variable]]
native_id = "346.30353"
slug = "familjeidentitet"

[[variable]]
native_id = "346.30770"
slug = "agarkategori-bostad"

# register 348
