[register]
provider = "scb"
slug = "solel"
native_id = "359"

[[variant]]
native_id = "359.1287"
slug = "_default"
display_group = "Nätanslutna solcellsanläggningar"
panel_entity_key = "knr"
panel_time_key = "period"
panel_time_grain = "delivery"

# Körsträckor med svenskregistrerade fordon

[[variable]]
native_id = "359.23923"
slug = "knr"


[[variable]]
native_id = "359.400"
slug = "adress"

# register 366 (utbildningsanalyser)

[[variable]]
native_id = "359.412"
slug = "postort"

[[variable]]
native_id = "359.1654"
slug = "kontaktperson-mobilnr"

[[variable]]
native_id = "359.2014"
slug = "foretagsnamn"

[[variable]]
native_id = "359.3752"
slug = "kontaktperson"

[[variable]]
native_id = "359.35643"
slug = "epost-kontaktperson"

# register 361
