"""Steward-flavored DB overlay — ``extend-db`` (#365 PR2).

Build a *steward-flavored* reg_meta DB by overlaying steward-ONLY content onto
a **released global DB**. The global DB (built by ``build-db`` from SCB/SOS) is
a READ-ONLY input: ``extend_db`` copies it, INSERTS the steward's own
registers/variables on the copy, and writes the result to a new directory. The
released global DB is never mutated.

The flavor carries ONLY content that exists for one steward and nowhere else:
new providers and the registers/variables they deliver (e.g. SWECOV's
bank-delivery registers). Enrichment of EXISTING GLOBAL entities — backfilling
a global variable's description, recording a pseudonym alias on a global
variable, or grafting a shared SCB/SOS column — is GLOBAL-build work and lives
in the shipped PR1 mechanisms (``delivery_enrichment.py`` for descriptions and
aliases, ``variable_grafts.py`` for shared-column grafts), NOT here: a fact
about a global register belongs in the global build regardless of which steward
surfaced it.

This is the ARCHITECTURE PR: the machinery + synthetic-fixture proof. It ships
ZERO real steward content — the real SWECOV inventory is generated by an
(untracked) generator that targets the JSON contract documented below.

Inventory JSON contract
------------------------
``extend_db`` reads a single JSON file (the inventory) the generator produces::

    {
      "steward": "swecov",
      "source_label": "swecov-inventory-2025-12-11",
      "providers": [
        {"slug": "swedbank", "name": "Swedbank AB"}
      ],
      "registers": [
        {
          "provider": "swedbank", "key": "transaktioner",
          "name": "Transaktioner", "purpose": null, "description": null,
          "variants": [
            {
              "key": "_default", "name": "Transaktioner", "description": null,
              "variables": [
                {
                  "key": "belopp", "name": "Belopp", "definition": null,
                  "description": "Transaktionsbelopp i SEK.",
                  "column": "BELOPP", "data_type": "float",
                  "is_identifier": false, "is_sensitive": false,
                  "valid_from": null, "valid_to": null
                }
              ]
            }
          ]
        }
      ]
    }

Top-level keys: ``steward`` (required str), ``source_label`` (required str —
stamped on every inserted ``variable.source_label``), and the two optional
operation arrays ``providers`` / ``registers`` (each may be absent or empty).
Any OTHER top-level key is a structural defect.

Operation kinds
---------------
1. **providers** — a steward-private data provider (a bank, an insurer). Minted
   ``provider_id = mint("provider", slug)`` (high band); INSERT-skipped if the
   slug already exists (idempotent; a slug/name mismatch fails like
   ``seed_providers``).
2. **registers/variants/variables/states** (nested) — the steward-private core
   graph. Deterministically minted high-band ids; inserted via the same column
   lists ``_reinsert_core_graph_from_ir`` uses. Each variable gets one
   open-range ``variable_state`` carrying its delivery ``column``, and that
   column also gets a ``variable_alias`` row (the ``variable_alias ⊇ state
   columns`` invariant — an intrinsic part of defining the steward variable,
   NOT an alias onto a global variable). The register's ``provider`` must be
   defined in ``providers[]`` or already live in the DB.

Discipline
----------
* **Strict load.** A structural inventory defect (unknown top-level key, missing
  required field) fails with ``EXIT_CONFIG``. Steward-only content has no
  FQID-resolution step — an unknown provider on a register is a hard structural
  error, not a lenient ``unresolved`` count.
* **No-clobber.** The overlay only INSERTs steward-only rows. It never UPDATEs
  or DELETEs a global row — global registers/variants/variables and their slugs
  are byte-identical after the overlay.
* **No ``SCHEMA_VERSION`` bump** — rows on existing tables only.
"""

from __future__ import annotations

import json
import shutil
import sqlite3
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from reg_meta.db import DB_FILENAME
from reg_meta.errors import EXIT_CONFIG, RegMetaError
from reg_meta.fqid import FqidError, FqidKind, period_token_to_bounds, validate_slug

from .id import mint

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

# Open-range sentinel for an inserted state whose inventory gives no validity
# window — mirrors `variable_grafts` and the DDL `valid_to` default.
_OPEN_FROM = "0001-01-01"
_OPEN_TO = "9999-12-31"


def _expand_window(valid_from: str | None, valid_to: str | None) -> tuple[str, str]:
    """Expand the inventory's ISO 8601 ``valid_from`` / ``valid_to`` (each one of
    ``YYYY`` | ``YYYY-MM`` | ``YYYY-MM-DD`` | a period token, or None) to the
    full ten-char ISO date bounds ``variable_state`` requires (the DDL CHECKs
    ``length(valid_from)=10``). Mirrors the materializer's coarse-form expansion
    via ``period_token_to_bounds`` so a steward state's bounds agree with a
    later period query. A None end falls back to the open sentinel. A
    malformed token is a structural inventory defect (EXIT_CONFIG)."""

    def _expand(token: str | None, *, end: str, default: str) -> str:
        if token is None:
            return default
        try:
            lo, hi = period_token_to_bounds(token)
        except FqidError as exc:
            raise _cfg_error(
                f"extend-db inventory validity token {token!r} is not a valid "
                f"ISO 8601 period: {exc}",
                "Use YYYY, YYYY-MM, YYYY-MM-DD, or a period token.",
            ) from exc
        return hi if end == "hi" else lo

    lo = _expand(valid_from, end="lo", default=_OPEN_FROM)
    hi = _expand(valid_to, end="hi", default=_OPEN_TO)
    # An inverted window would violate the `variable_state` DDL CHECK
    # (valid_to >= valid_from) and surface as an opaque sqlite3.IntegrityError
    # at INSERT time — far from the inventory. Catch it here as a clean
    # structural defect (ISO 8601 strings sort lexically == chronologically).
    if lo > hi:
        raise _cfg_error(
            f"extend-db inventory validity window is inverted: valid_from "
            f"{valid_from!r} ({lo}) is after valid_to {valid_to!r} ({hi}).",
            "Make valid_from <= valid_to (or omit one for an open end).",
        )
    return (lo, hi)


# ---------------------------------------------------------------------------
# Inventory contract (dataclasses — this surface stays Pydantic-free per
# ARCHITECTURE.md; only the build-time IR is Pydantic, and we adapt INTO it
# for the core-graph emit).
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InvProvider:
    slug: str
    name: str


@dataclass(frozen=True)
class InvVariable:
    key: str
    name: str
    column: str
    definition: str | None
    description: str | None
    data_type: str | None
    is_identifier: bool
    is_sensitive: bool
    valid_from: str | None
    valid_to: str | None


@dataclass(frozen=True)
class InvVariant:
    key: str
    name: str
    description: str | None
    variables: tuple[InvVariable, ...]


@dataclass(frozen=True)
class InvRegister:
    provider: str
    key: str
    name: str
    purpose: str | None
    description: str | None
    variants: tuple[InvVariant, ...]


@dataclass(frozen=True)
class Inventory:
    steward: str
    source_label: str
    providers: tuple[InvProvider, ...]
    registers: tuple[InvRegister, ...]


# ---------------------------------------------------------------------------
# Loader (strict — structural defects are EXIT_CONFIG)
# ---------------------------------------------------------------------------


def _cfg_error(message: str, remediation: str) -> RegMetaError:
    return RegMetaError(
        exit_code=EXIT_CONFIG,
        code="extend_inventory_invalid",
        error_class="configuration",
        message=message,
        remediation=remediation,
    )


def _require_str(obj: dict, field: str, context: str) -> str:
    value = obj.get(field)
    if not isinstance(value, str) or not value.strip():
        raise _cfg_error(
            f"extend-db inventory {context} needs `{field}` as a non-empty "
            f"string, got {value!r}.",
            f'Give `"{field}": "<value>"` in the inventory JSON.',
        )
    return value.strip()


def _opt_str(obj: dict, field: str, context: str) -> str | None:
    value = obj.get(field)
    if value is None:
        return None
    if not isinstance(value, str):
        raise _cfg_error(
            f"extend-db inventory {context} `{field}` must be a string or null, "
            f"got {value!r}.",
            f'Give `"{field}": "<value>"` or `null`.',
        )
    stripped = value.strip()
    return stripped or None


def _opt_bool(obj: dict, field: str, context: str) -> bool:
    value = obj.get(field, False)
    if not isinstance(value, bool):
        raise _cfg_error(
            f"extend-db inventory {context} `{field}` must be a bool, got {value!r}.",
            f'Give `"{field}": true` / `false` or omit it.',
        )
    return value


def _reject_unknown_keys(obj: dict, allowed: frozenset[str], context: str) -> None:
    unknown = sorted(set(obj) - allowed)
    if unknown:
        raise _cfg_error(
            f"extend-db inventory {context} has unknown key(s): {unknown}.",
            f"Remove them; allowed keys are {sorted(allowed)}.",
        )


_INV_TOPLEVEL = frozenset({"steward", "source_label", "providers", "registers"})
_PROVIDER_KEYS = frozenset({"slug", "name"})
_REGISTER_KEYS = frozenset(
    {"provider", "key", "name", "purpose", "description", "variants"}
)
_VARIANT_KEYS = frozenset({"key", "name", "description", "variables"})
_VARIABLE_KEYS = frozenset(
    {
        "key",
        "name",
        "definition",
        "description",
        "column",
        "data_type",
        "is_identifier",
        "is_sensitive",
        "valid_from",
        "valid_to",
    }
)


def _list_of_dicts(raw: Any, context: str) -> list[dict]:
    if raw is None:
        return []
    if not isinstance(raw, list) or not all(isinstance(e, dict) for e in raw):
        raise _cfg_error(
            f"extend-db inventory `{context}` must be a list of objects, got "
            f"{type(raw).__name__}.",
            f'Give `"{context}": [ ... ]` (or omit it).',
        )
    return raw


def load_inventory(path: Path) -> Inventory:
    """Parse + strictly validate the inventory JSON. Structural defects raise
    ``RegMetaError(EXIT_CONFIG)``. Steward-only content has no FQID-resolution
    step: an unknown provider on a register is a hard structural error at
    materialize time (``_insert_core_graph``), not a lenient ``unresolved``
    count."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise _cfg_error(
            f"Could not read extend-db inventory {path}: {exc}",
            "Ensure the file exists and is valid JSON.",
        ) from exc
    if not isinstance(raw, dict):
        raise _cfg_error(
            f"extend-db inventory {path} must be a JSON object.",
            "Wrap the inventory in a top-level object.",
        )
    _reject_unknown_keys(raw, _INV_TOPLEVEL, "(top level)")
    steward = _require_str(raw, "steward", "(top level)")
    source_label = _require_str(raw, "source_label", "(top level)")

    providers = tuple(
        _load_provider(p, i)
        for i, p in enumerate(_list_of_dicts(raw.get("providers"), "providers"))
    )
    registers = tuple(
        _load_register(r, i)
        for i, r in enumerate(_list_of_dicts(raw.get("registers"), "registers"))
    )

    _reject_duplicate_provider_slugs(providers)
    _validate_provider_slugs(providers)
    _reject_duplicate_register_keys(registers)

    return Inventory(
        steward=steward,
        source_label=source_label,
        providers=providers,
        registers=registers,
    )


def _load_provider(obj: dict, idx: int) -> InvProvider:
    ctx = f"providers[{idx}]"
    _reject_unknown_keys(obj, _PROVIDER_KEYS, ctx)
    return InvProvider(
        slug=_require_str(obj, "slug", ctx),
        name=_require_str(obj, "name", ctx),
    )


def _load_register(obj: dict, idx: int) -> InvRegister:
    ctx = f"registers[{idx}]"
    _reject_unknown_keys(obj, _REGISTER_KEYS, ctx)
    provider = _require_str(obj, "provider", ctx)
    key = _require_str(obj, "key", ctx)
    variants_raw = _list_of_dicts(obj.get("variants"), f"{ctx}.variants")
    if not variants_raw:
        raise _cfg_error(
            f"extend-db inventory {ctx} ({provider}/{key}) needs at least one variant.",
            'Give `"variants": [ { "key": "_default", ... } ]`.',
        )
    return InvRegister(
        provider=provider,
        key=key,
        name=_require_str(obj, "name", ctx),
        purpose=_opt_str(obj, "purpose", ctx),
        description=_opt_str(obj, "description", ctx),
        variants=tuple(
            _load_variant(v, provider, key, i) for i, v in enumerate(variants_raw)
        ),
    )


def _load_variant(obj: dict, provider: str, reg_key: str, idx: int) -> InvVariant:
    ctx = f"registers[{provider}/{reg_key}].variants[{idx}]"
    _reject_unknown_keys(obj, _VARIANT_KEYS, ctx)
    key = _require_str(obj, "key", ctx)
    variables_raw = _list_of_dicts(obj.get("variables"), f"{ctx}.variables")
    if not variables_raw:
        raise _cfg_error(
            f"extend-db inventory {ctx} needs at least one variable.",
            'Give `"variables": [ { "key": "...", ... } ]`.',
        )
    seen: set[str] = set()
    variables: list[InvVariable] = []
    for i, v in enumerate(variables_raw):
        var = _load_variable(v, ctx, i)
        if var.key in seen:
            raise _cfg_error(
                f"extend-db inventory {ctx} has duplicate variable key {var.key!r}.",
                "Each variable key must be unique within its variant.",
            )
        seen.add(var.key)
        variables.append(var)
    return InvVariant(
        key=key,
        name=_require_str(obj, "name", ctx),
        description=_opt_str(obj, "description", ctx),
        variables=tuple(variables),
    )


def _load_variable(obj: dict, variant_ctx: str, idx: int) -> InvVariable:
    ctx = f"{variant_ctx}.variables[{idx}]"
    _reject_unknown_keys(obj, _VARIABLE_KEYS, ctx)
    key = _require_str(obj, "key", ctx)
    # The variable key becomes `variable.provider_key`, and the slug source-ID
    # grammar uses '.' as its segment separator — `populate_variable_slugs.
    # _source_id` raises `slug_toml_invalid` on any '.' in a provider_key, a
    # confusing failure far from the inventory. Reject it here (register/variant
    # keys only feed `mint()`, so they're exempt).
    if "." in key:
        raise _cfg_error(
            f"extend-db inventory {ctx} variable key {key!r} must not contain '.' "
            "(it becomes the variable provider_key, whose slug source-ID grammar "
            "uses '.' as a segment separator).",
            "Rename the variable key so it has no dot.",
        )
    return InvVariable(
        key=key,
        name=_require_str(obj, "name", ctx),
        column=_require_str(obj, "column", ctx),
        definition=_opt_str(obj, "definition", ctx),
        description=_opt_str(obj, "description", ctx),
        data_type=_opt_str(obj, "data_type", ctx),
        is_identifier=_opt_bool(obj, "is_identifier", ctx),
        is_sensitive=_opt_bool(obj, "is_sensitive", ctx),
        valid_from=_opt_str(obj, "valid_from", ctx),
        valid_to=_opt_str(obj, "valid_to", ctx),
    )


def _reject_duplicate_provider_slugs(providers: tuple[InvProvider, ...]) -> None:
    seen: set[str] = set()
    for p in providers:
        if p.slug in seen:
            raise _cfg_error(
                f"extend-db inventory declares provider slug {p.slug!r} twice.",
                "Each provider slug must appear once.",
            )
        seen.add(p.slug)


def _validate_provider_slugs(providers: tuple[InvProvider, ...]) -> None:
    """Reject any overlay provider slug that fails reg_meta's authoritative slug
    rules for the PROVIDER slot. Unlike the steward register/variant slugs (which
    pass through `populate_slugs` → `validate_slug` when loaded from the steward
    TOML) and the variable slugs (auto-derived grammar-safe by `derive_variable_
    slug`), an inventory provider slug is INSERTed RAW by `_insert_providers` with
    no slug-grammar gate — so an overlay declaring e.g. a provider named `group`
    (reserved in the provider slot since #617: it would shadow the
    `/catalog/group/{provider}/{register}/{key}` route) or any grammar-invalid
    slug would re-open the route collision the reservation closes. Validate here
    at the LOAD boundary so the defect fails fast as a clean EXIT_CONFIG, far from
    the eventual URL-routing collision (Codex P2 on #622)."""
    for p in providers:
        try:
            validate_slug(p.slug, FqidKind.PROVIDER)
        except FqidError as exc:
            raise _cfg_error(
                f"extend-db inventory provider slug {p.slug!r} is not a valid "
                f"provider slug: {exc}",
                "Rename the provider to a valid, non-reserved slug.",
            ) from exc


def _reject_duplicate_register_keys(registers: tuple[InvRegister, ...]) -> None:
    seen: set[tuple[str, str]] = set()
    for r in registers:
        key = (r.provider, r.key)
        if key in seen:
            raise _cfg_error(
                f"extend-db inventory declares register {r.provider}/{r.key} twice.",
                "Each (provider, register key) must appear once.",
            )
        seen.add(key)


# ---------------------------------------------------------------------------
# Insert-only writer
# ---------------------------------------------------------------------------


def _provider_id_by_slug(conn: sqlite3.Connection) -> dict[str, int]:
    return {
        slug: pid
        for pid, slug in conn.execute("SELECT provider_id, slug FROM provider")
    }


def _insert_providers(
    conn: sqlite3.Connection, providers: tuple[InvProvider, ...]
) -> int:
    """Mint + INSERT steward providers. Idempotent: an already-present slug is
    skipped (verify the name matches, like ``seed_providers``)."""
    existing = dict(conn.execute("SELECT slug, name FROM provider"))
    inserted = 0
    for p in providers:
        if p.slug in existing:
            if existing[p.slug] != p.name:
                raise _cfg_error(
                    f"extend-db provider {p.slug!r} already present with name "
                    f"{existing[p.slug]!r}, inventory gives {p.name!r}.",
                    "Reconcile the provider name with the live DB.",
                )
            continue
        conn.execute(
            "INSERT INTO provider (provider_id, slug, name) VALUES (?, ?, ?)",
            (mint("provider", p.slug), p.slug, p.name),
        )
        inserted += 1
    return inserted


def _insert_core_graph(
    conn: sqlite3.Connection,
    registers: tuple[InvRegister, ...],
    *,
    source_label: str,
) -> dict[str, int]:
    """INSERT the steward-private core graph (registers/variants/variables/
    states + the per-state alias row). Ids are deterministically minted
    high-band; the column lists mirror ``_reinsert_core_graph_from_ir`` (the
    materializer's sole-writer INSERTs). Parity with that writer (a nullable
    column added here but not there silently leaves the other's rows unset) is
    locked by ``test_extend_db.py::TestCoreGraphInsertParity``. Slugs insert
    NULL — the steward TOML / incremental auto-derive fills them afterwards.

    Each register's provider must resolve to a live ``provider_id`` (a steward
    provider just inserted, or a built-in). A register whose provider is
    unknown is a structural defect (the inventory should have declared it)."""
    counts = {"registers": 0, "variants": 0, "variables": 0, "states": 0}
    provider_ids = _provider_id_by_slug(conn)

    for reg in registers:
        provider_id = provider_ids.get(reg.provider)
        if provider_id is None:
            raise _cfg_error(
                f"extend-db register {reg.provider}/{reg.key} names provider "
                f"{reg.provider!r}, which is neither declared in `providers` nor "
                "live in the DB.",
                "Declare the provider in the inventory `providers` array.",
            )
        register_id = mint("register", reg.provider, reg.key)
        conn.execute(
            "INSERT INTO register (register_id, provider_id, name, purpose, slug) "
            "VALUES (?, ?, ?, ?, NULL)",
            (register_id, provider_id, reg.name, reg.purpose),
        )
        counts["registers"] += 1

        for variant in reg.variants:
            register_variant_id = mint("variant", reg.provider, reg.key, variant.key)
            conn.execute(
                "INSERT INTO register_variant "
                "(register_variant_id, register_id, name, description, slug) "
                "VALUES (?, ?, ?, ?, NULL)",
                (register_variant_id, register_id, variant.name, variant.description),
            )
            counts["variants"] += 1

            for var in variant.variables:
                variable_id = mint(
                    "variable", reg.provider, reg.key, variant.key, var.key
                )
                conn.execute(
                    "INSERT INTO variable "
                    "(variable_id, register_id, provider_key, slug, name, "
                    " definition, description, operational_definition, "
                    " source_register_text, "
                    " measurement_unit, source_register_id, source_label, "
                    " is_sensitive, is_identifier) "
                    # operational_definition NULL: a steward inventory carries no
                    # SCB-style per-column operational definition (#892).
                    "VALUES (?, ?, ?, NULL, ?, ?, ?, NULL, NULL, NULL, NULL, ?, ?, ?)",
                    (
                        variable_id,
                        register_id,
                        var.key,  # provider_key: the steward's variable key
                        var.name,
                        var.definition,
                        var.description,
                        source_label,
                        int(var.is_sensitive),
                        int(var.is_identifier),
                    ),
                )
                counts["variables"] += 1

                state_id = mint("state", reg.provider, reg.key, variant.key, var.key)
                valid_from, valid_to = _expand_window(var.valid_from, var.valid_to)
                conn.execute(
                    "INSERT INTO variable_state "
                    "(state_id, variable_id, register_variant_id, valid_from, "
                    " valid_to, data_type, data_length, delivery_column_name, "
                    " value_set_id, value_set_version_label, classification_id) "
                    "VALUES (?, ?, ?, ?, ?, ?, NULL, ?, NULL, '', NULL)",
                    (
                        state_id,
                        variable_id,
                        register_variant_id,
                        valid_from,
                        valid_to,
                        var.data_type,
                        var.column,
                    ),
                )
                counts["states"] += 1
                # Preserve the `variable_alias ⊇ state delivery columns`
                # invariant: every state column is also an alias row.
                conn.execute(
                    "INSERT INTO variable_alias "
                    "(variable_id, register_variant_id, delivery_column_name) "
                    "VALUES (?, ?, ?)",
                    (variable_id, register_variant_id, var.column),
                )
    return counts


def _assert_steward_rows_slugged(conn: sqlite3.Connection) -> None:
    """Fail (EXIT_CONFIG) if any steward (non-SCB/SOS provider) ``register`` or
    ``register_variant`` row is left NULL-slug after slug population.

    ``populate_slugs(strict=False)`` is intentionally lenient (it must not touch
    the published global scb/sos rows), so a steward register/variant whose slug
    TOML entry is missing slips through silently — and nothing downstream catches
    it, so an unaddressable steward FQID would ship. Built-in global providers
    (scb/sos) are EXCLUDED: their slugs come from the global build, not the
    steward dir, and are not this overlay's concern."""
    missing: list[str] = []
    for row in conn.execute(
        "SELECT 'register', p.slug, r.register_id, r.name FROM register r "
        "JOIN provider p ON p.provider_id = r.provider_id "
        "WHERE p.slug NOT IN ('scb', 'sos') AND r.slug IS NULL "
        "ORDER BY r.register_id"
    ):
        missing.append(f"register {row[1]}#{row[2]} ({row[3]!r})")
    for row in conn.execute(
        "SELECT 'register_variant', p.slug, rv.register_variant_id, rv.name "
        "FROM register_variant rv "
        "JOIN register r ON r.register_id = rv.register_id "
        "JOIN provider p ON p.provider_id = r.provider_id "
        "WHERE p.slug NOT IN ('scb', 'sos') AND rv.slug IS NULL "
        "ORDER BY rv.register_variant_id"
    ):
        missing.append(f"register_variant {row[1]}#{row[2]} ({row[3]!r})")
    if missing:
        sample = "; ".join(missing[:5])
        raise _cfg_error(
            f"{len(missing)} steward register/variant row(s) have no slug after "
            f"slug population. Sample: {sample}.",
            "Add the missing [register] / [register_variant] entries to the "
            "steward slug dir, or pass --skip-slugs.",
        )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def resolve_steward_slug_dir(
    slug_dir: Path | None, steward: str, *, skip_slugs: bool
) -> Path | None:
    """Resolve the steward slug dir, or ``None`` when ``skip_slugs``.

    Shared by ``extend_db()`` and the CLI so the flavored validate hook reads the
    SAME dir the overlay populated. When ``skip_slugs`` is set, slug population is
    off entirely, so there is no dir to resolve (``None``). Otherwise resolves an
    explicit ``slug_dir`` (expanduser/resolve) or the repo's
    ``fqid_slugs/<steward>/``, raising the same ``RegMetaError``s the inline
    resolution did: ``extend_slug_dir_not_found`` when there's no repo checkout
    and no ``--slug-dir``, and again when the resolved path is not a directory."""
    if skip_slugs:
        return None
    if slug_dir is not None:
        resolved = slug_dir.expanduser().resolve()
    else:
        # Lazy import — the module already lazy-imports `fqid_slugs` inside
        # `extend_db` to dodge the import cycle.
        from .fqid_slugs import repo_slug_dir

        global_dir = repo_slug_dir()
        if global_dir is None:
            raise RegMetaError(
                exit_code=EXIT_CONFIG,
                code="extend_slug_dir_not_found",
                error_class="configuration",
                message=(
                    "No --slug-dir given and no repo checkout found for the "
                    f"steward slug dir (fqid_slugs/{steward}/)."
                ),
                remediation=(
                    "Pass --slug-dir, run from a repo checkout, or use --skip-slugs."
                ),
            )
        resolved = global_dir / steward
    if not resolved.is_dir():
        raise RegMetaError(
            exit_code=EXIT_CONFIG,
            code="extend_slug_dir_not_found",
            error_class="configuration",
            message=f"Steward slug dir not found: {resolved}",
            remediation=(
                f"Create fqid_slugs/{steward}/ (defaults to churning) or "
                "pass --skip-slugs."
            ),
        )
    return resolved


def extend_db(
    base_db: Path,
    inventory_path: Path,
    db_dir: Path,
    *,
    steward: str,
    slug_dir: Path | None = None,
    skip_slugs: bool = False,
    pre_rename_hook: Callable[[Path], None] | None = None,
) -> dict[str, Any]:
    """Build a steward-flavored DB by overlaying ``inventory_path`` onto the
    released global DB ``base_db``, writing the result to ``<db_dir>/reg_meta.db``.

    Mirrors ``build_db``'s file discipline: copy the base DB to a ``.tmp``,
    insert on the copy (``foreign_keys=OFF`` during inserts, FK-check before
    commit), run ``pre_rename_hook`` against the tmp, then atomically rotate +
    rename into place. No VACUUM (the overlay is insert-only — see the commit
    block). The base DB is a READ-ONLY input, never mutated.

    ``steward`` selects the steward slug dir
    (``reg_meta_build/fqid_slugs/<steward>/`` from a repo checkout) unless
    ``slug_dir`` is given; ``skip_slugs`` skips slug population entirely.

    Returns a counts dict: ``{providers, registers, variants, variables,
    states}``.
    """
    from .db import (
        _populate_fts,
        _progress,
        _unlink_wal_sidecars,
        rotate_db_to_prev,
    )
    from .fqid_slugs import populate_slugs, populate_variable_slugs

    base_db = base_db.expanduser().resolve()
    db_dir = db_dir.expanduser().resolve()
    inventory_path = inventory_path.expanduser().resolve()

    if not base_db.is_file():
        raise RegMetaError(
            exit_code=EXIT_CONFIG,
            code="extend_base_db_not_found",
            error_class="configuration",
            message=f"Base global DB not found: {base_db}",
            remediation="Pass --base-db pointing at a released reg_meta.db.",
        )

    # The base DB is a READ-ONLY input, but the end-of-run `rotate_db_to_prev`
    # moves whatever sits at the output path aside — so if `--base-db` resolves
    # to the output `reg_meta.db`, that rotate would silently move the "read-only"
    # base. Reject the overlap up front.
    if base_db == (db_dir / DB_FILENAME):
        raise RegMetaError(
            exit_code=EXIT_CONFIG,
            code="extend_base_db_is_output",
            error_class="configuration",
            message=(
                f"--base-db {base_db} resolves to the output DB path; the base is "
                "read-only and must differ from the output."
            ),
            remediation="Point --db at a different output directory.",
        )

    inventory = load_inventory(inventory_path)
    if inventory.steward != steward:
        raise _cfg_error(
            f"extend-db inventory steward {inventory.steward!r} does not match the "
            f"requested steward {steward!r}.",
            "Pass --steward matching the inventory, or fix the inventory.",
        )

    # Resolve the steward slug dir up front (before any file work) so a missing
    # dir fails fast rather than after the copy. Idempotent — the CLI resolves the
    # same dir and feeds it to both this call and the flavored validate hook.
    steward_slug_dir = resolve_steward_slug_dir(
        slug_dir, steward, skip_slugs=skip_slugs
    )

    db_dir.mkdir(parents=True, exist_ok=True)
    final_path = db_dir / DB_FILENAME
    tmp_path = final_path.with_suffix(".db.tmp")
    if tmp_path.exists():
        tmp_path.unlink()

    # The base DB is a read-only INPUT — copy2 (preserves mtime) so the source
    # is never opened for write. All inserts happen on the copy.
    shutil.copy2(base_db, tmp_path)

    conn = sqlite3.connect(tmp_path)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.execute("PRAGMA temp_store=MEMORY")
    conn.execute("PRAGMA foreign_keys=OFF")  # re-validate after inserts
    write_failed = True
    counts: dict[str, int] = {
        "providers": 0,
        "registers": 0,
        "variants": 0,
        "variables": 0,
        "states": 0,
    }
    try:
        _progress(f"extend-db: overlaying steward {steward!r} onto {base_db.name}")
        counts["providers"] = _insert_providers(conn, inventory.providers)
        core = _insert_core_graph(
            conn, inventory.registers, source_label=inventory.source_label
        )
        counts.update(core)

        if not skip_slugs:
            assert steward_slug_dir is not None  # resolved above when not skipping
            # Additive register/variant slug population: strict=False because the
            # steward dir intentionally does NOT cover scb/sos (their rows keep
            # their published global slugs untouched — UPDATE only matches steward
            # TOML entries).
            populate_slugs(conn, steward_slug_dir, strict=False)
            # Incremental variable slugs: derive ONLY the new (NULL-slug)
            # variables, uniquifying against the published global slugs.
            populate_variable_slugs(conn, steward_slug_dir, incremental=True)
            # `populate_slugs(strict=False)` silently leaves a steward register/
            # variant NULL-slug when the steward dir lacks its entry, and no
            # flavored-validation check catches it → an unaddressable steward
            # FQID would ship. Guard the steward (non-SCB/SOS) provider rows
            # here. Variables always auto-slug (incremental fallback chain), so
            # only registers + variants need the check.
            _assert_steward_rows_slugged(conn)

        # FTS rebuild: the overlay only INSERTs register / variable rows, so
        # those two indexes need a content-synced rebuild — cheap (a few extra
        # rows over the base) and avoids partial-sync bugs. These are
        # EXTERNAL-CONTENT FTS5 tables (content='register' etc.), so the index is
        # cleared with the special `'delete-all'` command — a plain
        # `DELETE FROM <fts>` corrupts an external-content index ("database disk
        # image is malformed"). value_code_fts is DELIBERATELY skipped: the
        # overlay never inserts a `value_code` row (grafts/aliases/steward
        # variables carry no value sets), so the index copied from the base DB is
        # already in sync — rebuilding it would re-insert ~4M rows for nothing on
        # a real flavored DB (#365 PR2 review).
        for fts in ("register_fts", "variable_fts"):
            conn.execute(f"INSERT INTO {fts}({fts}) VALUES('delete-all')")
        _populate_fts(conn, include_value_code=False)

        violations = list(conn.execute("PRAGMA foreign_key_check"))
        if violations:
            sample = ", ".join(f"{v[0]}#{v[1]}" for v in violations[:5])
            raise RegMetaError(
                exit_code=EXIT_CONFIG,
                code="foreign_key_violation",
                error_class="configuration",
                message=(
                    f"PRAGMA foreign_key_check returned {len(violations)} "
                    f"violation(s) before commit. Sample: {sample}."
                ),
                remediation=(
                    "The overlay inserted a row whose FK target is missing — "
                    "inspect the inventory's register/variant references."
                ),
            )
        conn.execute("PRAGMA foreign_keys=ON")
        conn.commit()
        # NO VACUUM: unlike `build_db` (which VACUUMs to reclaim pages freed by
        # its build-time-only DROP TABLEs), this overlay is INSERT-only and drops
        # nothing, so a VACUUM would rewrite the whole multi-GB copy of the global
        # DB to reclaim ~nothing — a dominant cost on the real flavored build. The
        # FTS delete-all + repopulate churns a few pages, but freelist stays far
        # below the validator's >=1% staging-bloat ceiling.
        write_failed = False
    finally:
        conn.close()
        if write_failed:
            tmp_path.unlink(missing_ok=True)

    # Pre-rename hook (flavored validation) runs against the tmp so a failure
    # aborts before the rename. The base global DB is untouched regardless.
    if pre_rename_hook is not None:
        try:
            pre_rename_hook(tmp_path)
        except BaseException:
            tmp_path.unlink(missing_ok=True)
            _unlink_wal_sidecars(tmp_path)
            raise

    _unlink_wal_sidecars(tmp_path)
    rotate_db_to_prev(final_path)
    tmp_path.rename(final_path)
    _progress(f"Flavored database written to {final_path}")

    # The contract return is the int counts dict; `db_path` rides alongside for
    # the CLI envelope (separate dict so `counts` stays homogeneously int-typed).
    result: dict[str, Any] = {**counts, "db_path": str(final_path)}
    return result
