"""Steward-flavored DB overlay — ``extend-db`` (#365 PR2).

Build a *steward-flavored* reg_meta DB by overlaying steward-private content
onto a **released global DB**. The global DB (built by ``build-db`` from
SCB/SOS) is a READ-ONLY input: ``extend_db`` copies it, INSERTS the steward's
overlay on the copy, and writes the result to a new directory. The released
global DB is never mutated.

Where PR1 (``delivery_enrichment.py``) and PR1d (``variable_grafts.py``) carry
facts about the *shared* SCB/SOS world into the GLOBAL build, this overlay is
the steward-PRIVATE world: registers and variables that exist only for one
steward's flavor (e.g. SWECOV's bank-delivery registers), plus
pseudonym-column aliases and SCB-graft columns that the steward documents but
the global build doesn't carry.

This is the ARCHITECTURE PR: the machinery + synthetic-fixture proof. It ships
ZERO real steward content — the real SWECOV inventory is generated by an
(untracked) generator that targets the JSON contract documented below.

Inventory JSON contract
------------------------
``extend_db`` reads a single JSON file (the inventory) the generator produces::

    {
      "steward": "swecov",
      "source_label": "swecov-inventory-2025-12-11",
      "providers": [
        {"slug": "swedbank", "name": "Swedbank AB"}
      ],
      "registers": [
        {
          "provider": "swedbank", "key": "transaktioner",
          "name": "Transaktioner", "purpose": null, "description": null,
          "variants": [
            {
              "key": "_default", "name": "Transaktioner", "description": null,
              "variables": [
                {
                  "key": "belopp", "name": "Belopp", "definition": null,
                  "description": "Transaktionsbelopp i SEK.",
                  "column": "BELOPP", "data_type": "float",
                  "is_identifier": false, "is_sensitive": false,
                  "valid_from": null, "valid_to": null
                }
              ]
            }
          ]
        }
      ],
      "grafts": [
        {"register": "scb/agi", "variant": "agi-default",
         "column": "LANDSKOD_X", "name": "...", "description": "...",
         "data_type": "varchar"}
      ],
      "aliases": [
        {"variable": "scb/rtb/personnr", "register": "scb/rtb",
         "variant": "rtb-default", "delivery_column": "P1105_LopNr_PersonNr"}
      ]
    }

Top-level keys: ``steward`` (required str), ``source_label`` (required str —
stamped on every inserted/grafted ``variable.source_label``), and the four
optional operation arrays ``providers`` / ``registers`` / ``grafts`` /
``aliases`` (each may be absent or empty). Any OTHER top-level key is a
structural defect.

Operation kinds
---------------
1. **providers** — a steward-private data provider (a bank, an insurer). Minted
   ``provider_id = mint("provider", slug)`` (high band); INSERT-skipped if the
   slug already exists (idempotent; a slug/name mismatch fails like
   ``seed_providers``).
2. **registers/variants/variables/states** (nested) — the steward-private core
   graph. Deterministically minted high-band ids; inserted via the same column
   lists ``_reinsert_core_graph_from_ir`` uses. Each variable gets one
   open-range ``variable_state`` carrying its delivery ``column``, and that
   column also gets a ``variable_alias`` row (the ``variable_alias ⊇ state
   columns`` invariant). The register's ``provider`` must be defined in
   ``providers[]`` or already live in the DB.
3. **grafts** — a real column of a canonical SCB/SOS register the steward
   delivers (mirrors ``variable_grafts.materialize_grafts``). Gap-fill: skipped
   if the column already exists as a state column in that ``(register,
   variant)``. Minted in the TARGET provider's band — SCB → sequential just
   above the live SCB max (``< 2^62``); steward/SOS → ``mint()``.
4. **aliases** — a delivery-column alias on an EXISTING variable resolved by
   3-segment FQID (mirrors ``delivery_enrichment._apply_aliases``). INSERT OR
   IGNORE on every variant in which the variable has a state. This is where
   ``P1105_LopNr_*`` pseudonym names land.

Discipline
----------
* **Strict load, lenient resolve.** A structural inventory defect (unknown
  top-level key, missing required field, malformed FQID) fails with
  ``EXIT_CONFIG``. A graft/alias whose target FQID doesn't resolve is counted
  ``unresolved``, not fatal (mirrors the global overlays).
* **No-clobber.** The overlay only INSERTs. It never UPDATEs or DELETEs a
  global row — global registers/variants/variables and their slugs are
  byte-identical after the overlay.
* **No ``SCHEMA_VERSION`` bump** — rows on existing tables only.
"""

from __future__ import annotations

import json
import shutil
import sqlite3
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from reg_meta.db import DB_FILENAME
from reg_meta.errors import EXIT_CONFIG, RegMetaError
from reg_meta.fqid import FqidError, period_token_to_bounds

from .id import _MINT_BIT, mint

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

# Open-range sentinel for an inserted state whose inventory gives no validity
# window — mirrors `variable_grafts` and the DDL `valid_to` default.
_OPEN_FROM = "0001-01-01"
_OPEN_TO = "9999-12-31"


def _expand_window(valid_from: str | None, valid_to: str | None) -> tuple[str, str]:
    """Expand the inventory's ISO 8601 ``valid_from`` / ``valid_to`` (each one of
    ``YYYY`` | ``YYYY-MM`` | ``YYYY-MM-DD`` | a period token, or None) to the
    full ten-char ISO date bounds ``variable_state`` requires (the DDL CHECKs
    ``length(valid_from)=10``). Mirrors the materializer's coarse-form expansion
    via ``period_token_to_bounds`` so a steward state's bounds agree with a
    later period query. A None end falls back to the open sentinel. A
    malformed token is a structural inventory defect (EXIT_CONFIG)."""

    def _expand(token: str | None, *, end: str, default: str) -> str:
        if token is None:
            return default
        try:
            lo, hi = period_token_to_bounds(token)
        except FqidError as exc:
            raise _cfg_error(
                f"extend-db inventory validity token {token!r} is not a valid "
                f"ISO 8601 period: {exc}",
                "Use YYYY, YYYY-MM, YYYY-MM-DD, or a period token.",
            ) from exc
        return hi if end == "hi" else lo

    return (
        _expand(valid_from, end="lo", default=_OPEN_FROM),
        _expand(valid_to, end="hi", default=_OPEN_TO),
    )


# ---------------------------------------------------------------------------
# Inventory contract (dataclasses — this surface stays Pydantic-free per
# ARCHITECTURE.md; only the build-time IR is Pydantic, and we adapt INTO it
# for the core-graph emit).
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InvProvider:
    slug: str
    name: str


@dataclass(frozen=True)
class InvVariable:
    key: str
    name: str
    column: str
    definition: str | None
    description: str | None
    data_type: str | None
    is_identifier: bool
    is_sensitive: bool
    valid_from: str | None
    valid_to: str | None


@dataclass(frozen=True)
class InvVariant:
    key: str
    name: str
    description: str | None
    variables: tuple[InvVariable, ...]


@dataclass(frozen=True)
class InvRegister:
    provider: str
    key: str
    name: str
    purpose: str | None
    description: str | None
    variants: tuple[InvVariant, ...]


@dataclass(frozen=True)
class InvGraft:
    register_fqid: str  # 2-seg provider/register
    provider: str
    register: str
    variant: str
    column: str
    name: str
    description: str | None
    data_type: str | None


@dataclass(frozen=True)
class InvAlias:
    variable_fqid: str  # 3-seg provider/register/variable
    provider: str
    register: str
    variable: str
    delivery_column: str


@dataclass(frozen=True)
class Inventory:
    steward: str
    source_label: str
    providers: tuple[InvProvider, ...]
    registers: tuple[InvRegister, ...]
    grafts: tuple[InvGraft, ...]
    aliases: tuple[InvAlias, ...]


# ---------------------------------------------------------------------------
# Loader (strict — structural defects are EXIT_CONFIG)
# ---------------------------------------------------------------------------


def _cfg_error(message: str, remediation: str) -> RegMetaError:
    return RegMetaError(
        exit_code=EXIT_CONFIG,
        code="extend_inventory_invalid",
        error_class="configuration",
        message=message,
        remediation=remediation,
    )


def _require_str(obj: dict, field: str, context: str) -> str:
    value = obj.get(field)
    if not isinstance(value, str) or not value.strip():
        raise _cfg_error(
            f"extend-db inventory {context} needs `{field}` as a non-empty "
            f"string, got {value!r}.",
            f'Give `"{field}": "<value>"` in the inventory JSON.',
        )
    return value.strip()


def _opt_str(obj: dict, field: str, context: str) -> str | None:
    value = obj.get(field)
    if value is None:
        return None
    if not isinstance(value, str):
        raise _cfg_error(
            f"extend-db inventory {context} `{field}` must be a string or null, "
            f"got {value!r}.",
            f'Give `"{field}": "<value>"` or `null`.',
        )
    stripped = value.strip()
    return stripped or None


def _opt_bool(obj: dict, field: str, context: str) -> bool:
    value = obj.get(field, False)
    if not isinstance(value, bool):
        raise _cfg_error(
            f"extend-db inventory {context} `{field}` must be a bool, got {value!r}.",
            f'Give `"{field}": true` / `false` or omit it.',
        )
    return value


def _reject_unknown_keys(obj: dict, allowed: frozenset[str], context: str) -> None:
    unknown = sorted(set(obj) - allowed)
    if unknown:
        raise _cfg_error(
            f"extend-db inventory {context} has unknown key(s): {unknown}.",
            f"Remove them; allowed keys are {sorted(allowed)}.",
        )


_INV_TOPLEVEL = frozenset(
    {"steward", "source_label", "providers", "registers", "grafts", "aliases"}
)
_PROVIDER_KEYS = frozenset({"slug", "name"})
_REGISTER_KEYS = frozenset(
    {"provider", "key", "name", "purpose", "description", "variants"}
)
_VARIANT_KEYS = frozenset({"key", "name", "description", "variables"})
_VARIABLE_KEYS = frozenset(
    {
        "key",
        "name",
        "definition",
        "description",
        "column",
        "data_type",
        "is_identifier",
        "is_sensitive",
        "valid_from",
        "valid_to",
    }
)
_GRAFT_KEYS = frozenset(
    {"register", "variant", "column", "name", "description", "data_type"}
)
_ALIAS_KEYS = frozenset({"variable", "register", "variant", "delivery_column"})


def _list_of_dicts(raw: Any, context: str) -> list[dict]:
    if raw is None:
        return []
    if not isinstance(raw, list) or not all(isinstance(e, dict) for e in raw):
        raise _cfg_error(
            f"extend-db inventory `{context}` must be a list of objects, got "
            f"{type(raw).__name__}.",
            f'Give `"{context}": [ ... ]` (or omit it).',
        )
    return raw


def _split_fqid(value: str, n_segments: int, context: str) -> tuple[str, ...]:
    parts = value.split("/")
    if len(parts) != n_segments or not all(parts):
        raise _cfg_error(
            f"extend-db inventory {context} {value!r} must be a "
            f"{n_segments}-segment FQID.",
            "Give a `provider/register`-style FQID."
            if n_segments == 2
            else "Give a `provider/register/variable`-style FQID.",
        )
    return tuple(parts)


def load_inventory(path: Path) -> Inventory:
    """Parse + strictly validate the inventory JSON. Structural defects raise
    ``RegMetaError(EXIT_CONFIG)``; reference RESOLUTION (does the graft/alias
    target exist?) is deferred to materialize time (lenient)."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise _cfg_error(
            f"Could not read extend-db inventory {path}: {exc}",
            "Ensure the file exists and is valid JSON.",
        ) from exc
    if not isinstance(raw, dict):
        raise _cfg_error(
            f"extend-db inventory {path} must be a JSON object.",
            "Wrap the inventory in a top-level object.",
        )
    _reject_unknown_keys(raw, _INV_TOPLEVEL, "(top level)")
    steward = _require_str(raw, "steward", "(top level)")
    source_label = _require_str(raw, "source_label", "(top level)")

    providers = tuple(
        _load_provider(p, i)
        for i, p in enumerate(_list_of_dicts(raw.get("providers"), "providers"))
    )
    registers = tuple(
        _load_register(r, i)
        for i, r in enumerate(_list_of_dicts(raw.get("registers"), "registers"))
    )
    grafts = tuple(
        _load_graft(g, i)
        for i, g in enumerate(_list_of_dicts(raw.get("grafts"), "grafts"))
    )
    aliases = tuple(
        _load_alias(a, i)
        for i, a in enumerate(_list_of_dicts(raw.get("aliases"), "aliases"))
    )

    _reject_duplicate_provider_slugs(providers)
    _reject_duplicate_register_keys(registers)

    return Inventory(
        steward=steward,
        source_label=source_label,
        providers=providers,
        registers=registers,
        grafts=grafts,
        aliases=aliases,
    )


def _load_provider(obj: dict, idx: int) -> InvProvider:
    ctx = f"providers[{idx}]"
    _reject_unknown_keys(obj, _PROVIDER_KEYS, ctx)
    return InvProvider(
        slug=_require_str(obj, "slug", ctx),
        name=_require_str(obj, "name", ctx),
    )


def _load_register(obj: dict, idx: int) -> InvRegister:
    ctx = f"registers[{idx}]"
    _reject_unknown_keys(obj, _REGISTER_KEYS, ctx)
    provider = _require_str(obj, "provider", ctx)
    key = _require_str(obj, "key", ctx)
    variants_raw = _list_of_dicts(obj.get("variants"), f"{ctx}.variants")
    if not variants_raw:
        raise _cfg_error(
            f"extend-db inventory {ctx} ({provider}/{key}) needs at least one variant.",
            'Give `"variants": [ { "key": "_default", ... } ]`.',
        )
    return InvRegister(
        provider=provider,
        key=key,
        name=_require_str(obj, "name", ctx),
        purpose=_opt_str(obj, "purpose", ctx),
        description=_opt_str(obj, "description", ctx),
        variants=tuple(
            _load_variant(v, provider, key, i) for i, v in enumerate(variants_raw)
        ),
    )


def _load_variant(obj: dict, provider: str, reg_key: str, idx: int) -> InvVariant:
    ctx = f"registers[{provider}/{reg_key}].variants[{idx}]"
    _reject_unknown_keys(obj, _VARIANT_KEYS, ctx)
    key = _require_str(obj, "key", ctx)
    variables_raw = _list_of_dicts(obj.get("variables"), f"{ctx}.variables")
    if not variables_raw:
        raise _cfg_error(
            f"extend-db inventory {ctx} needs at least one variable.",
            'Give `"variables": [ { "key": "...", ... } ]`.',
        )
    seen: set[str] = set()
    variables: list[InvVariable] = []
    for i, v in enumerate(variables_raw):
        var = _load_variable(v, ctx, i)
        if var.key in seen:
            raise _cfg_error(
                f"extend-db inventory {ctx} has duplicate variable key {var.key!r}.",
                "Each variable key must be unique within its variant.",
            )
        seen.add(var.key)
        variables.append(var)
    return InvVariant(
        key=key,
        name=_require_str(obj, "name", ctx),
        description=_opt_str(obj, "description", ctx),
        variables=tuple(variables),
    )


def _load_variable(obj: dict, variant_ctx: str, idx: int) -> InvVariable:
    ctx = f"{variant_ctx}.variables[{idx}]"
    _reject_unknown_keys(obj, _VARIABLE_KEYS, ctx)
    return InvVariable(
        key=_require_str(obj, "key", ctx),
        name=_require_str(obj, "name", ctx),
        column=_require_str(obj, "column", ctx),
        definition=_opt_str(obj, "definition", ctx),
        description=_opt_str(obj, "description", ctx),
        data_type=_opt_str(obj, "data_type", ctx),
        is_identifier=_opt_bool(obj, "is_identifier", ctx),
        is_sensitive=_opt_bool(obj, "is_sensitive", ctx),
        valid_from=_opt_str(obj, "valid_from", ctx),
        valid_to=_opt_str(obj, "valid_to", ctx),
    )


def _load_graft(obj: dict, idx: int) -> InvGraft:
    ctx = f"grafts[{idx}]"
    _reject_unknown_keys(obj, _GRAFT_KEYS, ctx)
    register_fqid = _require_str(obj, "register", ctx)
    provider, register = _split_fqid(register_fqid, 2, f"{ctx} register")
    return InvGraft(
        register_fqid=register_fqid,
        provider=provider,
        register=register,
        variant=_require_str(obj, "variant", ctx),
        column=_require_str(obj, "column", ctx),
        name=_require_str(obj, "name", ctx),
        description=_opt_str(obj, "description", ctx),
        data_type=_opt_str(obj, "data_type", ctx),
    )


def _load_alias(obj: dict, idx: int) -> InvAlias:
    ctx = f"aliases[{idx}]"
    _reject_unknown_keys(obj, _ALIAS_KEYS, ctx)
    variable_fqid = _require_str(obj, "variable", ctx)
    provider, register, variable = _split_fqid(variable_fqid, 3, f"{ctx} variable")
    return InvAlias(
        variable_fqid=variable_fqid,
        provider=provider,
        register=register,
        variable=variable,
        delivery_column=_require_str(obj, "delivery_column", ctx),
    )


def _reject_duplicate_provider_slugs(providers: tuple[InvProvider, ...]) -> None:
    seen: set[str] = set()
    for p in providers:
        if p.slug in seen:
            raise _cfg_error(
                f"extend-db inventory declares provider slug {p.slug!r} twice.",
                "Each provider slug must appear once.",
            )
        seen.add(p.slug)


def _reject_duplicate_register_keys(registers: tuple[InvRegister, ...]) -> None:
    seen: set[tuple[str, str]] = set()
    for r in registers:
        key = (r.provider, r.key)
        if key in seen:
            raise _cfg_error(
                f"extend-db inventory declares register {r.provider}/{r.key} twice.",
                "Each (provider, register key) must appear once.",
            )
        seen.add(key)


# ---------------------------------------------------------------------------
# Insert-only writer
# ---------------------------------------------------------------------------


def _provider_id_by_slug(conn: sqlite3.Connection) -> dict[str, int]:
    return {
        slug: pid
        for pid, slug in conn.execute("SELECT provider_id, slug FROM provider")
    }


def _insert_providers(
    conn: sqlite3.Connection, providers: tuple[InvProvider, ...]
) -> int:
    """Mint + INSERT steward providers. Idempotent: an already-present slug is
    skipped (verify the name matches, like ``seed_providers``)."""
    existing = dict(conn.execute("SELECT slug, name FROM provider"))
    inserted = 0
    for p in providers:
        if p.slug in existing:
            if existing[p.slug] != p.name:
                raise _cfg_error(
                    f"extend-db provider {p.slug!r} already present with name "
                    f"{existing[p.slug]!r}, inventory gives {p.name!r}.",
                    "Reconcile the provider name with the live DB.",
                )
            continue
        conn.execute(
            "INSERT INTO provider (provider_id, slug, name) VALUES (?, ?, ?)",
            (mint("provider", p.slug), p.slug, p.name),
        )
        inserted += 1
    return inserted


def _insert_core_graph(
    conn: sqlite3.Connection,
    registers: tuple[InvRegister, ...],
    *,
    source_label: str,
) -> dict[str, int]:
    """INSERT the steward-private core graph (registers/variants/variables/
    states + the per-state alias row). Ids are deterministically minted
    high-band; the column lists mirror ``_reinsert_core_graph_from_ir`` (the
    materializer's sole-writer INSERTs). Slugs insert NULL — the steward TOML /
    incremental auto-derive fills them afterwards.

    Each register's provider must resolve to a live ``provider_id`` (a steward
    provider just inserted, or a built-in). A register whose provider is
    unknown is a structural defect (the inventory should have declared it)."""
    counts = {"registers": 0, "variants": 0, "variables": 0, "states": 0}
    provider_ids = _provider_id_by_slug(conn)

    for reg in registers:
        provider_id = provider_ids.get(reg.provider)
        if provider_id is None:
            raise _cfg_error(
                f"extend-db register {reg.provider}/{reg.key} names provider "
                f"{reg.provider!r}, which is neither declared in `providers` nor "
                "live in the DB.",
                "Declare the provider in the inventory `providers` array.",
            )
        register_id = mint("register", reg.provider, reg.key)
        conn.execute(
            "INSERT INTO register (register_id, provider_id, name, purpose, slug) "
            "VALUES (?, ?, ?, ?, NULL)",
            (register_id, provider_id, reg.name, reg.purpose),
        )
        counts["registers"] += 1

        for variant in reg.variants:
            register_variant_id = mint("variant", reg.provider, reg.key, variant.key)
            conn.execute(
                "INSERT INTO register_variant "
                "(register_variant_id, register_id, name, description, slug) "
                "VALUES (?, ?, ?, ?, NULL)",
                (register_variant_id, register_id, variant.name, variant.description),
            )
            counts["variants"] += 1

            for var in variant.variables:
                variable_id = mint(
                    "variable", reg.provider, reg.key, variant.key, var.key
                )
                conn.execute(
                    "INSERT INTO variable "
                    "(variable_id, register_id, provider_key, slug, name, "
                    " definition, description, source_register_text, "
                    " measurement_unit, source_register_id, source_label, "
                    " is_sensitive, is_identifier) "
                    "VALUES (?, ?, ?, NULL, ?, ?, ?, NULL, NULL, NULL, ?, ?, ?)",
                    (
                        variable_id,
                        register_id,
                        var.key,  # provider_key: the steward's variable key
                        var.name,
                        var.definition,
                        var.description,
                        source_label,
                        int(var.is_sensitive),
                        int(var.is_identifier),
                    ),
                )
                counts["variables"] += 1

                state_id = mint("state", reg.provider, reg.key, variant.key, var.key)
                valid_from, valid_to = _expand_window(var.valid_from, var.valid_to)
                conn.execute(
                    "INSERT INTO variable_state "
                    "(state_id, variable_id, register_variant_id, valid_from, "
                    " valid_to, data_type, data_length, delivery_column_name, "
                    " value_set_id, value_set_version_label, classification_id) "
                    "VALUES (?, ?, ?, ?, ?, ?, NULL, ?, NULL, '', NULL)",
                    (
                        state_id,
                        variable_id,
                        register_variant_id,
                        valid_from,
                        valid_to,
                        var.data_type,
                        var.column,
                    ),
                )
                counts["states"] += 1
                # Preserve the `variable_alias ⊇ state delivery columns`
                # invariant: every state column is also an alias row.
                conn.execute(
                    "INSERT INTO variable_alias "
                    "(variable_id, register_variant_id, delivery_column_name) "
                    "VALUES (?, ?, ?)",
                    (variable_id, register_variant_id, var.column),
                )
    return counts


def _apply_grafts(
    conn: sqlite3.Connection,
    grafts: tuple[InvGraft, ...],
    *,
    source_label: str,
    warn: Callable[[str], None],
) -> dict[str, int]:
    """Mint variable+state+alias for each graft onto its EXISTING
    ``(register, variant)`` (resolved by slug FQID). Gap-fill: skip a column
    already delivered as a state column there (case/diacritic-folded via
    ``LOWER``, mirroring ``materialize_grafts``).

    Banding mirrors ``variable_grafts`` PER TARGET PROVIDER: an SCB-register
    graft gets sequential ids just above the live SCB max (stays ``< 2^62``);
    a steward/SOS-register graft is ``mint()``-ed into the high band. Reads the
    live max off the COPY, so SCB-band grafts never collide with shipped PR1d
    grafts already in the global DB."""
    counts = {"grafts_minted": 0, "grafts_skipped": 0, "unresolved": 0}
    if not grafts:
        return counts

    # SCB-band sequential counters (only consumed by SCB-register grafts). Read
    # off the COPY's live extrema so we sit just above PR1d's shipped grafts.
    next_scb_var = (
        conn.execute(
            "SELECT COALESCE(MAX(variable_id), 0) FROM variable WHERE variable_id < ?",
            (_MINT_BIT,),
        ).fetchone()[0]
        + 1
    )
    next_scb_state = (
        conn.execute(
            "SELECT COALESCE(MAX(state_id), 0) FROM variable_state WHERE state_id < ?",
            (_MINT_BIT,),
        ).fetchone()[0]
        + 1
    )

    for g in grafts:
        variant_row = conn.execute(
            "SELECT rv.register_variant_id, r.register_id, p.slug "
            "FROM register_variant rv "
            "JOIN register r ON r.register_id = rv.register_id "
            "JOIN provider p ON p.provider_id = r.provider_id "
            "WHERE p.slug = ? AND r.slug = ? AND rv.slug = ?",
            (g.provider, g.register, g.variant),
        ).fetchone()
        if variant_row is None:
            counts["unresolved"] += 1
            continue
        register_variant_id, register_id, provider_slug = variant_row
        # Gap-fill only: skip if the column already delivers a state here.
        exists = conn.execute(
            "SELECT 1 FROM variable_state vs JOIN variable v "
            "ON vs.variable_id = v.variable_id "
            "WHERE v.register_id = ? AND vs.register_variant_id = ? "
            "AND LOWER(vs.delivery_column_name) = LOWER(?) LIMIT 1",
            (register_id, register_variant_id, g.column),
        ).fetchone()
        if exists:
            counts["grafts_skipped"] += 1
            continue

        if provider_slug == "scb":
            variable_id = next_scb_var
            state_id = next_scb_state
            next_scb_var += 1
            next_scb_state += 1
            if variable_id >= _MINT_BIT:  # pragma: no cover — pathological corpus
                raise _cfg_error(
                    "extend-db SCB graft ids would overflow the SCB band (2^62).",
                    "Too many SCB variables to graft — investigate.",
                )
        else:
            # Steward/SOS register graft: mint into the high band, keyed on the
            # graft coordinate so re-runs are deterministic.
            variable_id = mint(
                "graft-variable", g.provider, g.register, g.variant, g.column
            )
            state_id = mint("graft-state", g.provider, g.register, g.variant, g.column)

        conn.execute(
            "INSERT INTO variable (variable_id, register_id, provider_key, name, "
            "description, source_label) VALUES (?, ?, ?, ?, ?, ?)",
            (
                variable_id,
                register_id,
                f"graft:{g.column}",
                g.name,
                g.description,
                source_label,
            ),
        )
        conn.execute(
            "INSERT INTO variable_state (state_id, variable_id, register_variant_id, "
            "valid_from, valid_to, data_type, delivery_column_name) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (
                state_id,
                variable_id,
                register_variant_id,
                _OPEN_FROM,
                _OPEN_TO,
                g.data_type,
                g.column,
            ),
        )
        conn.execute(
            "INSERT INTO variable_alias (variable_id, register_variant_id, "
            "delivery_column_name) VALUES (?, ?, ?)",
            (variable_id, register_variant_id, g.column),
        )
        counts["grafts_minted"] += 1

    if counts["unresolved"]:
        warn(
            f"  WARN extend-db: {counts['unresolved']:,} graft(s) did not resolve "
            "(register/variant slug churn) — regenerate the steward inventory"
        )
    return counts


def _apply_aliases(
    conn: sqlite3.Connection,
    aliases: tuple[InvAlias, ...],
    *,
    warn: Callable[[str], None],
) -> dict[str, int]:
    """INSERT OR IGNORE a ``variable_alias`` row on every variant in which the
    target variable (resolved by 3-seg FQID) has a state — mirrors
    ``delivery_enrichment._apply_aliases``. Idempotent; a slug that doesn't
    resolve (or a variable with no state) is counted ``unresolved``."""
    counts = {"aliases": 0, "unresolved": 0}
    for al in aliases:
        variable_row = conn.execute(
            "SELECT v.variable_id FROM variable v "
            "JOIN register r ON v.register_id = r.register_id "
            "JOIN provider p ON r.provider_id = p.provider_id "
            "WHERE p.slug = ? AND r.slug = ? AND v.slug = ?",
            (al.provider, al.register, al.variable),
        ).fetchone()
        variant_rows = conn.execute(
            "SELECT DISTINCT vs.register_variant_id FROM variable_state vs "
            "JOIN variable v ON vs.variable_id = v.variable_id "
            "JOIN register r ON v.register_id = r.register_id "
            "JOIN provider p ON r.provider_id = p.provider_id "
            "WHERE p.slug = ? AND r.slug = ? AND v.slug = ?",
            (al.provider, al.register, al.variable),
        ).fetchall()
        if variable_row is None or not variant_rows:
            counts["unresolved"] += 1
            continue
        variable_id = variable_row[0]
        for (register_variant_id,) in variant_rows:
            cur = conn.execute(
                "INSERT OR IGNORE INTO variable_alias "
                "(variable_id, register_variant_id, delivery_column_name) "
                "VALUES (?, ?, ?)",
                (variable_id, register_variant_id, al.delivery_column),
            )
            if cur.rowcount:
                counts["aliases"] += 1
    if counts["unresolved"]:
        warn(
            f"  WARN extend-db: {counts['unresolved']:,} alias(es) did not resolve "
            "(slug churn / no state) — regenerate the steward inventory"
        )
    return counts


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def extend_db(
    base_db: Path,
    inventory_path: Path,
    db_dir: Path,
    *,
    steward: str,
    slug_dir: Path | None = None,
    skip_slugs: bool = False,
    pre_rename_hook: Callable[[Path], None] | None = None,
) -> dict[str, Any]:
    """Build a steward-flavored DB by overlaying ``inventory_path`` onto the
    released global DB ``base_db``, writing the result to ``<db_dir>/reg_meta.db``.

    Mirrors ``build_db``'s file discipline: copy the base DB to a ``.tmp``,
    insert on the copy (``foreign_keys=OFF`` during inserts, FK-check + VACUUM
    before commit), run ``pre_rename_hook`` against the tmp, then atomically
    rotate + rename into place. The base DB is a READ-ONLY input, never mutated.

    ``steward`` selects the steward slug dir
    (``reg_meta_build/fqid_slugs/<steward>/`` from a repo checkout) unless
    ``slug_dir`` is given; ``skip_slugs`` skips slug population entirely.

    Returns a counts dict: ``{providers, registers, variants, variables,
    states, aliases, grafts_minted, grafts_skipped, unresolved}``.
    """
    from .db import _populate_fts, _progress, rotate_db_to_prev
    from .fqid_slugs import populate_slugs, populate_variable_slugs, repo_slug_dir

    base_db = base_db.expanduser().resolve()
    db_dir = db_dir.expanduser().resolve()
    inventory_path = inventory_path.expanduser().resolve()

    if not base_db.is_file():
        raise RegMetaError(
            exit_code=EXIT_CONFIG,
            code="extend_base_db_not_found",
            error_class="configuration",
            message=f"Base global DB not found: {base_db}",
            remediation="Pass --base-db pointing at a released reg_meta.db.",
        )

    inventory = load_inventory(inventory_path)
    if inventory.steward != steward:
        raise _cfg_error(
            f"extend-db inventory steward {inventory.steward!r} does not match the "
            f"requested steward {steward!r}.",
            "Pass --steward matching the inventory, or fix the inventory.",
        )

    # Resolve the steward slug dir up front (before any file work) so a missing
    # dir fails fast rather than after the copy.
    steward_slug_dir: Path | None = None
    if not skip_slugs:
        if slug_dir is not None:
            steward_slug_dir = slug_dir.expanduser().resolve()
        else:
            global_dir = repo_slug_dir()
            if global_dir is None:
                raise RegMetaError(
                    exit_code=EXIT_CONFIG,
                    code="extend_slug_dir_not_found",
                    error_class="configuration",
                    message=(
                        "No --slug-dir given and no repo checkout found for the "
                        f"steward slug dir (fqid_slugs/{steward}/)."
                    ),
                    remediation=(
                        "Pass --slug-dir, run from a repo checkout, or "
                        "use --skip-slugs."
                    ),
                )
            steward_slug_dir = global_dir / steward
        if not steward_slug_dir.is_dir():
            raise RegMetaError(
                exit_code=EXIT_CONFIG,
                code="extend_slug_dir_not_found",
                error_class="configuration",
                message=f"Steward slug dir not found: {steward_slug_dir}",
                remediation=(
                    f"Create fqid_slugs/{steward}/ (with an UNFROZEN sentinel) or "
                    "pass --skip-slugs."
                ),
            )

    db_dir.mkdir(parents=True, exist_ok=True)
    final_path = db_dir / DB_FILENAME
    tmp_path = final_path.with_suffix(".db.tmp")
    if tmp_path.exists():
        tmp_path.unlink()

    # The base DB is a read-only INPUT — copy2 (preserves mtime) so the source
    # is never opened for write. All inserts happen on the copy.
    shutil.copy2(base_db, tmp_path)

    conn = sqlite3.connect(tmp_path)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.execute("PRAGMA temp_store=MEMORY")
    conn.execute("PRAGMA foreign_keys=OFF")  # re-validate after inserts
    write_failed = True
    counts: dict[str, int] = {
        "providers": 0,
        "registers": 0,
        "variants": 0,
        "variables": 0,
        "states": 0,
        "aliases": 0,
        "grafts_minted": 0,
        "grafts_skipped": 0,
        "unresolved": 0,
    }
    try:
        _progress(f"extend-db: overlaying steward {steward!r} onto {base_db.name}")
        counts["providers"] = _insert_providers(conn, inventory.providers)
        core = _insert_core_graph(
            conn, inventory.registers, source_label=inventory.source_label
        )
        counts.update(core)
        graft_counts = _apply_grafts(
            conn, inventory.grafts, source_label=inventory.source_label, warn=_progress
        )
        alias_counts = _apply_aliases(conn, inventory.aliases, warn=_progress)
        counts["grafts_minted"] = graft_counts["grafts_minted"]
        counts["grafts_skipped"] = graft_counts["grafts_skipped"]
        counts["aliases"] = alias_counts["aliases"]
        counts["unresolved"] = graft_counts["unresolved"] + alias_counts["unresolved"]

        if not skip_slugs:
            assert steward_slug_dir is not None  # resolved above when not skipping
            # Additive register/variant slug population: strict=False because the
            # steward dir intentionally does NOT cover scb/sos (their rows keep
            # their published global slugs untouched — UPDATE only matches steward
            # TOML entries).
            populate_slugs(conn, steward_slug_dir, strict=False)
            # Incremental variable slugs: derive ONLY the new (NULL-slug)
            # variables, uniquifying against the published global slugs.
            populate_variable_slugs(conn, steward_slug_dir, incremental=True)

        # FTS rebuild: the overlay only INSERTs register / variable rows, so
        # those two indexes need a content-synced rebuild — cheap (a few extra
        # rows over the base) and avoids partial-sync bugs. These are
        # EXTERNAL-CONTENT FTS5 tables (content='register' etc.), so the index is
        # cleared with the special `'delete-all'` command — a plain
        # `DELETE FROM <fts>` corrupts an external-content index ("database disk
        # image is malformed"). value_code_fts is DELIBERATELY skipped: the
        # overlay never inserts a `value_code` row (grafts/aliases/steward
        # variables carry no value sets), so the index copied from the base DB is
        # already in sync — rebuilding it would re-insert ~4M rows for nothing on
        # a real flavored DB (#365 PR2 review).
        for fts in ("register_fts", "variable_fts"):
            conn.execute(f"INSERT INTO {fts}({fts}) VALUES('delete-all')")
        _populate_fts(conn, include_value_code=False)

        violations = list(conn.execute("PRAGMA foreign_key_check"))
        if violations:
            sample = ", ".join(f"{v[0]}#{v[1]}" for v in violations[:5])
            raise RegMetaError(
                exit_code=EXIT_CONFIG,
                code="foreign_key_violation",
                error_class="configuration",
                message=(
                    f"PRAGMA foreign_key_check returned {len(violations)} "
                    f"violation(s) before commit. Sample: {sample}."
                ),
                remediation=(
                    "The overlay inserted a row whose FK target is missing — "
                    "inspect the inventory's register/variant references."
                ),
            )
        conn.execute("PRAGMA foreign_keys=ON")
        conn.commit()
        conn.execute("VACUUM")  # must run outside a transaction
        write_failed = False
    finally:
        conn.close()
        if write_failed:
            tmp_path.unlink(missing_ok=True)

    # Pre-rename hook (flavored validation) runs against the tmp so a failure
    # aborts before the rename. The base global DB is untouched regardless.
    if pre_rename_hook is not None:
        try:
            pre_rename_hook(tmp_path)
        except BaseException:
            tmp_path.unlink(missing_ok=True)
            _unlink_wal_sidecars(tmp_path)
            raise

    _unlink_wal_sidecars(tmp_path)
    rotate_db_to_prev(final_path)
    tmp_path.rename(final_path)
    _progress(f"Flavored database written to {final_path}")

    # The contract return is the int counts dict; `db_path` rides alongside for
    # the CLI envelope (separate dict so `counts` stays homogeneously int-typed).
    result: dict[str, Any] = {**counts, "db_path": str(final_path)}
    return result


def _unlink_wal_sidecars(db_path: Path) -> None:
    for sidecar in ("-wal", "-shm"):
        db_path.with_name(db_path.name + sidecar).unlink(missing_ok=True)
