"""Provider-blind interval co-delivery resolution engine (#271).

Claims in, owned intervals out (DESIGN.md → Interval-native co-delivery
resolution). No provider grammar lives here: claim windows arrive pre-parsed
(the SCB adapter derives them from `registerversionnamn` via
`_edition_bounds`), and every provider-convention judgment — which claims are
one drifted coding, who wins a contested segment — is injected through
`SweepHooks`. The SCB adapter is the only caller until a second provider
needs co-delivery resolution.

The model, per contested year and delivery column:

1. DRIFT CONFLATION (identity, per compaction window, blind to claim
   windows): a pool that is ONE drifted coding (`hooks.single_coding`)
   resolves via the caller's cascade (`hooks.resolve_pool`) to one carrier
   owning ITS OWN claim window; co-class losers are dropped — no carve, no
   run split. The compaction window is the `cadence` parameter: the whole
   year by default, single months under ``"month"``.
2. SEGMENT CHOICE (window-aware): a multi-coding pool's claim windows
   partition the year into atomic segments; each multi-claimant segment runs
   the caller's full cascade. Disjoint windows are NOT a conflict — both
   ship. A segment the cascade cannot resolve is returned as genuine.
3. RUN ASSEMBLY (`assemble_runs`, used by the caller's materializer): owned
   intervals form emission runs that break on a year with no owned interval
   (year-aligned edges) or at a rival-owned segment (precise carve edges).

Claim windows are year-nested and grammar-generated by contract: every bound
comes from `period_token_to_bounds` forms, so window ends are always
`_MONTH_LAST_DAY` month ends — including the SYNTHESIZED Feb-29 in non-leap
years, which `date.fromisoformat` would reject. The static successor tables
keep this module free of datetime entirely (and of that footgun).
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from typing import TYPE_CHECKING

from reg_meta.fqid import _MONTH_LAST_DAY

if TYPE_CHECKING:
    from collections.abc import Callable, Hashable

# Throughout: the type parameter `C` is the opaque candidate key the sweep
# resolves over (the SCB adapter passes its 9-tuple gkeys). The engine never
# introspects candidates — everything goes through the hooks — so the bound
# is only what dict/set membership needs.


@dataclass
class Claim:
    """One per-(state group, edition year) delivery claim: the inclusive ISO
    hull of the year's edition windows (a multi-edition year max-merges), plus
    the year's strongest authority rank and latest approval date. Year-nested
    by contract — a claim window never crosses a year boundary."""

    lo: str  # inclusive ISO start of the year's delivery hull
    hi: str  # inclusive ISO end
    authority: int  # provider authority rank, higher wins
    approval: str  # latest approval date (ISO; '' unknown)


_MONTH_NEXT = {f"{m:02d}": f"{m + 1:02d}" for m in range(1, 12)}


def day_after_window_end(hi: str) -> str:
    """The day after an inclusive grammar window end (always a month end)."""
    year, month, day = hi[:4], hi[5:7], hi[8:10]
    if _MONTH_LAST_DAY.get(month) != day:
        raise AssertionError(f"non-grammar claim window end: {hi!r}")
    if month == "12":
        return f"{int(year) + 1:04d}-01-01"
    return f"{year}-{_MONTH_NEXT[month]}-01"


def prev_day_from_cut(cut: str) -> str:
    """The inclusive end just before a cut point (a month first): the previous
    month's `_MONTH_LAST_DAY` end — the inverse of `day_after_window_end`."""
    year, month = cut[:4], cut[5:7]
    if cut[8:10] != "01":
        raise AssertionError(f"non-grammar cut point: {cut!r}")
    if month == "01":
        return f"{int(year) - 1:04d}-12-31"
    prev = f"{int(month) - 1:02d}"
    return f"{year}-{prev}-{_MONTH_LAST_DAY[prev]}"


def merge_adjacent(intervals: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Merge sorted inclusive intervals that touch (next lo == day after
    prev hi) or overlap into maximal contiguous intervals."""
    merged: list[tuple[str, str]] = []
    for lo, hi in intervals:
        if merged and lo <= day_after_window_end(merged[-1][1]):
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))
    return merged


def assemble_runs[C: Hashable](
    intervals: list[tuple[str, str]],
    rivals: list[tuple[str, str, C]],
) -> list[tuple[list[tuple[str, str]], bool, bool]]:
    """Group one column-owner's sorted owned intervals into emission runs.

    Returns ``(intervals, cut_in, cut_out)`` per run. A run breaks between two
    consecutive owned intervals when (a) a same-column RIVAL-owned interval
    intersects the open gap between them — the carve rule, edges emitted at
    the precise owned bounds (`cut_*` True; padding would overlap the rival) —
    or (b) the next interval starts more than one calendar year after the
    previous ends (the year-RLE rule; nobody owns the gap, so the edges stay
    year-aligned, `cut_*` False). Both at once counts as a carve: for
    year-grain losses the owned intervals are full years, so the precise edges
    coincide with the padded ones and the output is unchanged."""
    runs: list[tuple[list[tuple[str, str]], bool, bool]] = []
    cur = [intervals[0]]
    cur_cut_in = False
    for prev, nxt in zip(intervals, intervals[1:]):
        rival_between = any(
            r_hi > prev[1] and r_lo < nxt[0] for r_lo, r_hi, _ in rivals
        )
        if rival_between:
            runs.append((cur, cur_cut_in, True))
            cur, cur_cut_in = [nxt], True
        elif int(nxt[0][:4]) > int(prev[1][:4]) + 1:
            runs.append((cur, cur_cut_in, False))
            cur, cur_cut_in = [nxt], False
        else:
            cur.append(nxt)
    runs.append((cur, cur_cut_in, False))
    return runs


@dataclass(frozen=True)
class SweepHooks[C: Hashable]:
    """The provider conventions the sweep is parameterized over. Every hook
    closes over the caller's per-resolution context (its state groups, value
    -set accessors, curation maps, and the year under resolution)."""

    # A candidate's claim window for the year under resolution.
    window: Callable[[C], tuple[str, str]]
    # The candidate's delivery-column identity (parallel columns co-exist;
    # resolution is per column).
    column: Callable[[C], str]
    # Deterministic candidate ordering.
    sort_key: Callable[[C], tuple]
    # Whether the candidate carries a real (non-null) value set — code-less
    # shadows never own a contested segment by mere coverage.
    coded: Callable[[C], bool]
    # Pool-level identity verdict: is this pool ONE drifted coding?
    single_coding: Callable[[list[C]], bool]
    # The caller's full resolution cascade over a candidate pool →
    # (winners, genuine). Must dedup same-value-set candidates to one
    # representative and apply curation; `genuine` means >1 distinct value
    # set survived.
    resolve_pool: Callable[[list[C]], tuple[list[C], bool]]


def resolve_year_intervals[C: Hashable](
    cands: list[C],
    hooks: SweepHooks[C],
    cadence: str = "year",
) -> tuple[
    list[tuple[C, str, str]],
    list[tuple[str, str, str, list[C]]],
]:
    """Resolve one contested year at interval grain, column-aware.

    Returns ``(owned, genuine)``: ``owned`` as `(candidate, lo, hi)` interval
    triples in deterministic first-win order (the caller's emission order
    derives from it; a candidate may own several disjoint intervals of one
    year), ``genuine`` as `(column, seg_lo, seg_hi, candidates)` segments
    still holding >1 distinct value set after the caller's cascade."""
    by_col: dict[str, list[C]] = defaultdict(list)
    for gk in cands:
        by_col[hooks.column(gk)].append(gk)
    owned: list[tuple[C, str, str]] = []
    genuine: list[tuple[str, str, str, list[C]]] = []
    for col, col_cands in by_col.items():
        col_owned, col_genuine = _resolve_column_intervals(col_cands, hooks, cadence)
        owned.extend(col_owned)
        genuine.extend((col, lo, hi, gks) for lo, hi, gks in col_genuine)
    return owned, genuine


def _resolve_column_intervals[C: Hashable](
    cands: list[C],
    hooks: SweepHooks[C],
    cadence: str,
) -> tuple[
    list[tuple[C, str, str]],
    list[tuple[str, str, list[C]]],
]:
    """One column's claims: drift conflation at compaction-window grain, then
    segment choice where windows overlap (see the module docstring)."""
    # ── drift conflation ────────────────────────────────────────────────
    if cadence == "year":
        pools = [sorted(cands, key=hooks.sort_key)]
    else:  # month cadence: only claims fitting ONE month unit share a pool
        by_unit: dict[str | None, list[C]] = defaultdict(list)
        for gk in sorted(cands, key=hooks.sort_key):
            lo, hi = hooks.window(gk)
            unit = lo[:7] if lo[:7] == hi[:7] else None
            by_unit[unit].append(gk)
        pools = []
        for unit, gks in sorted(
            by_unit.items(), key=lambda kv: (kv[0] is None, kv[0] or "")
        ):
            if unit is None:
                # A window spanning >1 month is no single delivery period —
                # it never conflates; each such claim is its own pool.
                pools.extend([gk] for gk in gks)
            else:
                pools.append(gks)

    carriers: list[C] = []
    for pool in pools:
        if len(pool) > 1 and hooks.single_coding(pool):
            winners, genuine = hooks.resolve_pool(pool)
            if genuine:  # unreachable: a single-coding pool always collapses
                raise AssertionError(f"single-coding pool failed to conflate: {pool!r}")
            carriers.extend(winners)
        else:
            carriers.extend(pool)

    if len(carriers) == 1:
        lo, hi = hooks.window(carriers[0])
        return [(carriers[0], lo, hi)], []

    # ── segment choice ──────────────────────────────────────────────────
    cuts: set[str] = set()
    for gk in carriers:
        lo, hi = hooks.window(gk)
        cuts.add(lo)
        cuts.add(day_after_window_end(hi))
    bounds = sorted(cuts)
    owned: list[tuple[C, str, str]] = []
    genuine_segs: list[tuple[str, str, list[C]]] = []
    seg_owned: dict[C, list[tuple[str, str]]] = defaultdict(list)
    for seg_lo, seg_next in zip(bounds, bounds[1:]):
        covering = [
            gk
            for gk in carriers
            if hooks.window(gk)[0] <= seg_lo
            and seg_next <= day_after_window_end(hooks.window(gk)[1])
        ]
        if not covering:
            continue  # a gap between disjoint claim windows — unclaimed
        seg_hi = prev_day_from_cut(seg_next)
        # Segmentation only runs for multi-coding pools (≤1-distinct-coding
        # pools conflated above), so code-less claimants here are the shadows
        # the year bucket dropped whenever a coded rival took the year: they
        # never own by mere coverage, only by out-ranking through the cascade.
        if not any(hooks.coded(gk) for gk in covering):
            continue
        # ALWAYS the full cascade — even when the segment's claimants share
        # one value set. The cascade picks its same-set representative AFTER
        # its authority/recency filters; a bare latest-era shortcut here let a
        # sub-annual same-set sibling out-rep an annual one (caught on the
        # real corpus: GFBGrupp 2013 HT).
        winners, genuine = hooks.resolve_pool(covering)
        if genuine:
            genuine_segs.append((seg_lo, seg_hi, winners))
        else:
            # The winner may be code-less (it out-ranked every coded claimant
            # through the filters) — the year bucket let it own the year in
            # that case too, so no extra guard; mere-coverage shadows never
            # get this far (the cascade's coded pool always beats them).
            seg_owned[winners[0]].append((seg_lo, seg_hi))
    # Deterministic first-win order: carriers order, intervals merged.
    for gk in carriers:
        if gk in seg_owned:
            for lo, hi in merge_adjacent(sorted(seg_owned[gk])):
                owned.append((gk, lo, hi))
    return owned, genuine_segs
