version = 1
steward = "swecov"

[[table]]
id = "Annual2019"
edition = 2019
[[table.column]]
name = "Observed"
[[table.column.mapping]]
register_variant = "scb/example/annual"
variable = "scb/example/value"
representation = "Value"
