[register]
provider = "fk"
slug = "ersattning-sjuklonekostnader"
native_id = "7791929252178908414"

[[variant]]
native_id = "7791929252178908414.6117630078032501785"
slug = "_default"
display_group = "Ersättning för sjuklönekostnader"
panel_entity_key = "lopnr-orgnr"
panel_time_key = "utbetalningsmanad"
panel_time_grain = "row"

# Etableringsersättning

[[variable]]
native_id = "7791929252178908414.organisationsnummer"
slug = "lopnr-orgnr"
