[register]
provider = "fk"
slug = "etableringstillagg"
native_id = "5025807446792777547"

[[variant]]
native_id = "5025807446792777547.6060193209099644170"
slug = "_default"
display_group = "Etableringstillägg"
panel_entity_key = "lopnr-personnr"
panel_time_key = "utbetalningsmanad"
panel_time_grain = "row"

# Graviditetspenning

[[variable]]
native_id = "5025807446792777547.personnummer"
slug = "lopnr-personnr"
