[register]
provider = "fk"
slug = "graviditetspenning"
native_id = "7612505802412930990"

[[variant]]
native_id = "7612505802412930990.4921892111850379854"
slug = "_default"
display_group = "Graviditetspenning"
panel_entity_key = "lopnr-personnr"
panel_time_key = "utbetalningsmanad"
panel_time_grain = "row"

# Handikappersättning

[[variable]]
native_id = "7612505802412930990.personnummer"
slug = "lopnr-personnr"
