"""Generate `crates/reg-core/src/case_folding.rs` from the UCD `CaseFolding.txt`.

The table is full case folding (statuses C and F), the mapping Python's
`str.casefold()` applies. Statuses S (simple, superseded by F) and T (Turkic) are
skipped. The UCD file is pinned by version and SHA-256 and fetched only when this tool
runs; the build reads the committed output.

Run from the repository root:

    uv run python crates/reg-core/tools/gen_case_folding.py
    uv run python crates/reg-core/tools/gen_case_folding.py --source CaseFolding.txt

Before writing, the table is checked against Python's `str.casefold()` on every scalar
Python's UCD assigns. Python (3.14) is on an older UCD, so the scalars it leaves
unassigned are not checked; `conformance/cases/folds/unicode17.jsonl` covers them.
"""

from __future__ import annotations

import argparse
import hashlib
import unicodedata
import urllib.request
from pathlib import Path

UCD_VERSION = "17.0.0"
SOURCE_URL = f"https://www.unicode.org/Public/{UCD_VERSION}/ucd/CaseFolding.txt"
SOURCE_SHA256 = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183"
STATUSES = frozenset({"C", "F"})
OUTPUT = Path(__file__).resolve().parents[1] / "src" / "case_folding.rs"


def read_source(source: Path | None) -> bytes:
    if source is not None:
        return source.read_bytes()
    with urllib.request.urlopen(SOURCE_URL) as response:
        return response.read()


def parse(text: str) -> dict[int, tuple[list[int], str]]:
    """Code point -> (folded code points, character name) for statuses C and F."""
    table: dict[int, tuple[list[int], str]] = {}
    for line in text.splitlines():
        data, _, comment = line.partition("#")
        if not data.strip():
            continue
        code, status, mapping, _ = (field.strip() for field in data.split(";"))
        if status not in STATUSES:
            continue
        cp = int(code, 16)
        if cp in table:
            raise SystemExit(f"duplicate C/F mapping for U+{cp:04X}")
        table[cp] = ([int(m, 16) for m in mapping.split()], comment.strip())
    return table


def check_against_python(table: dict[int, tuple[list[int], str]]) -> None:
    """Fail unless the table agrees with `str.casefold()` wherever Python can judge."""
    mismatches = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        if unicodedata.category(ch) == "Cn":
            continue
        ours = "".join(map(chr, table[cp][0])) if cp in table else ch
        if ours != ch.casefold():
            mismatches.append(f"U+{cp:04X}")
    if mismatches:
        raise SystemExit(
            f"table disagrees with Python {unicodedata.unidata_version} casefold on "
            f"{len(mismatches)} assigned scalars: {', '.join(mismatches[:20])}"
        )


def rust_char(cp: int) -> str:
    return f"'\\u{{{cp:X}}}'"


def rust_str(cps: list[int]) -> str:
    return '"' + "".join(f"\\u{{{cp:X}}}" for cp in cps) + '"'


def render(table: dict[int, tuple[list[int], str]], sha256: str) -> str:
    major, minor, patch = UCD_VERSION.split(".")
    lines = [
        "// @generated by crates/reg-core/tools/gen_case_folding.py. Do not edit.",
        "//",
        f"// Source: {SOURCE_URL}",
        f"// UCD version: {UCD_VERSION}",
        f"// SHA-256: {sha256}",
        "// Statuses: C and F (full case folding, as Python's `str.casefold()`).",
        "",
        "/// Unicode version of the case-folding table.",
        f"pub const UNICODE_VERSION: (u8, u8, u8) = ({major}, {minor}, {patch});",
        "",
        "/// Full case folding, sorted by code point for binary search.",
        "#[rustfmt::skip]",
        "pub(crate) static CASE_FOLDING: &[(char, &str)] = &[",
    ]
    for cp in sorted(table):
        mapping, name = table[cp]
        lines.append(f"    ({rust_char(cp)}, {rust_str(mapping)}), // {name}")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--source", type=Path, help=f"local CaseFolding.txt ({UCD_VERSION})"
    )
    args = parser.parse_args()

    raw = read_source(args.source)
    sha256 = hashlib.sha256(raw).hexdigest()
    if sha256 != SOURCE_SHA256:
        raise SystemExit(f"CaseFolding.txt SHA-256 {sha256} != pinned {SOURCE_SHA256}")
    table = parse(raw.decode("utf-8"))
    check_against_python(table)
    OUTPUT.write_text(render(table, sha256), encoding="utf-8")
    print(f"wrote {len(table)} mappings to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
