from typing import Literal, final

class GrammarError(ValueError): ...

@final
class Fqid:
    @property
    def kind(self) -> Literal["provider", "register", "variable", "classification"]: ...
    @property
    def provider(self) -> str | None: ...
    @property
    def register(self) -> str | None: ...
    @property
    def variable(self) -> str | None: ...
    @property
    def classification(self) -> str | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def parse_fqid(value: str) -> Fqid: ...
def check_slug(value: str) -> None: ...
def is_period(value: str) -> bool: ...
def period_bounds(value: str) -> tuple[str, str]: ...
def fold_identity(s: str) -> str: ...
def fold_search(s: str) -> str: ...
