/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Mona Bundle
         * @description Build the MONA bundle embedding the posted ``project_data.json`` and return
         *     the ``.py`` bytes. Reads the raw dict (preserving namespaced blocks) and
         *     offloads the blocking build to the threadpool.
         */
        post: operations["build_mona_bundle_api_bundle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog Root
         * @description The catalog root: every provider plus the classification-root sentinel.
         */
        get: operations["get_catalog_root_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog Node
         * @description Resolve any catalog node by FQID path; on a binding leaf, an optional
         *     `?period` (with `?variant` / `?value_set_version`) narrows to the resolve_at
         *     state subset.
         *
         *     The guards (`_validated_fqid` for the path, `_validated_period` /
         *     `_validated_variant` for the queries) run as dependencies, BEFORE this body —
         *     so a malformed path OR a malformed period/variant returns 422 **before** any
         *     connection opens (zero SQL, zero opens). `parse` is DB-free and runs before
         *     the open too. The classification-root literal `class` (1 seg) is special-cased
         *     before `parse`.
         *
         *     `?period` semantics: present + binding leaf → `{states: [...]}` (the
         *     resolve_at subset, narrowed by `?variant` / `?value_set_version`; the #307
         *     comma list form resolves per segment, unioned + deduped by state_id). present +
         *     non-binding kind → IGNORED (resolve normally). absent on a binding leaf → the
         *     full node (full history) UNLESS a narrowing modifier (`?variant` /
         *     `?value_set_version`) is set: those are inert without `?period`, so they 422
         *     ("requires ?period") rather than silently no-op. absent on a non-binding kind →
         *     the full node. `?value_set_version` is a read-only browse-narrowing label
         *     filter — there is no FQID `@version` pin (retired). The connection is opened and
         *     used within this sync body (one thread — see `_catalog_conn`).
         */
        get: operations["get_catalog_node_api_catalog__fqid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binding Dimensions
         * @description Concept-group dimension memberships for this binding's variable (#489):
         *     the 'pick your variant' facet groups (level / population / rank / …) that
         *     contain it. Delegates to `Catalog.dimensions`, which resolves `same_as` like
         *     the sibling edge endpoints — an alias cites its resolved target's groups, not
         *     the requested register's. Binding-only (a non-binding kind 422s); a
         *     dead/renamed binding 301s to `/dimensions` on its terminal successor (#411).
         */
        get: operations["get_binding_dimensions_api_catalog__fqid__dimensions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binding Lineage
         * @description Consumer-side composite lineage edges (state grain — see
         *     reg_meta_build/DESIGN.md → Consumer-side lineage (variable_state_lineage)).
         *     Maps what reg_meta's `LineageEdge` carries; the richer per-source-state shape is a
         *     possible reg_meta enhancement (not blocked on here — see DESIGN.md). A
         *     dead/renamed binding 301s to `/lineage` on its terminal successor (#411).
         */
        get: operations["get_binding_lineage_api_catalog__fqid__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}/lineage_warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binding Lineage Warnings
         * @description Build-time lineage warnings for the binding. Empty when lineage
         *     resolved cleanly. The leaf does NOT embed these — this is their endpoint. A
         *     dead/renamed binding 301s to `/lineage_warnings` on its terminal successor
         *     (#411).
         */
        get: operations["get_binding_lineage_warnings_api_catalog__fqid__lineage_warnings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}/predecessors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binding Predecessors
         * @description Variables this binding's variable replaced (inbound succession). A
         *     dead/renamed binding 301s to `/predecessors` on its terminal successor (#411).
         */
        get: operations["get_binding_predecessors_api_catalog__fqid__predecessors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binding Related
         * @description Split-sibling variables (variable grain — see reg_meta_build/DESIGN.md →
         *     Build-time triage (SCB)). A dead/renamed binding 301s to `/related` on its
         *     terminal successor (#411).
         */
        get: operations["get_binding_related_api_catalog__fqid__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binding States
         * @description Full state history for a binding. ≡ the leaf's embedded `states`,
         *     standalone. Same shape the `?period` catch-all returns (codegen sees one
         *     state-list type). A dead/renamed binding 301s to `/states` on its terminal
         *     successor (#411).
         */
        get: operations["get_binding_states_api_catalog__fqid__states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{fqid}/successors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Binding Successors
         * @description Variables that replaced this binding's variable (outbound succession). A
         *     dead/renamed binding 301s to `/successors` on its terminal successor (#411).
         */
        get: operations["get_binding_successors_api_catalog__fqid__successors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{provider}/{register}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Register Variants
         * @description List a register's variants (the `?variant=` browse axis). `_default`
         *     is a real variant and IS returned (not filtered). 404 when the register
         *     doesn't resolve (so a typo'd register isn't a silent empty list).
         */
        get: operations["get_register_variants_api_catalog__provider___register__variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context */
        get: operations["get_context_api_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/doc/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Doc
         * @description One doc by variable name or filename — metadata + source pointer + a
         *     BOUNDED excerpt (never the full body). 404 when the docs index is absent
         *     (detail says so, distinct from a genuine not-found) or the doc isn't found.
         */
        get: operations["get_doc_api_docs_doc__identifier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/for-variable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Docs For Variable
         * @description The "mentioned in documentation" hook for a variable leaf: FUZZY
         *     name/provider_key text search over the docs index (the SPA passes the
         *     variable's provider_key and/or name as `q`, scoped to its register).
         *
         *     `register_ingested` encodes the coverage distinction — when the variable's
         *     register has no ingested docs (coverage is LISA-only), absence reads as "no
         *     docs ingested for this register", NOT "this variable is undocumented". Every
         *     result is flagged `fuzzy` (a heuristic text match, not an authoritative
         *     variable→doc link).
         */
        get: operations["get_docs_for_variable_api_docs_for_variable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Docs Search
         * @description Full-text docs search, optionally register-scoped. When the docs index is
         *     absent, `ingested=False` with empty results (NOT a 500) — "no docs ingested",
         *     distinct from an empty result set for a real query.
         */
        get: operations["get_docs_search_api_docs_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Kit
         * @description Build the generation kit from the posted ``project_data.json`` and return
         *     the ZIP bytes. Reads the raw dict (preserving namespaced blocks) and offloads
         *     the blocking validate-then-build to the threadpool.
         */
        post: operations["build_kit_api_kit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Order Project
         * @description Render the steward's default v1 order-export CSV.
         *
         *     Reads the raw dict and runs the STRUCTURAL gate (see reg_schema/DESIGN.md →
         *     Structural rules and issue codes) before rendering: the
         *     ``ProjectData`` model enforces only field types, while the structural rules
         *     (FQID shape, period grammar, the binding/source-prefix match) live in
         *     ``validate_structural`` — so a Pydantic-valid-but-structurally-invalid spec
         *     (e.g. a malformed ``register_variant`` or bad period token) would otherwise
         *     render a bad provider order at 200. A structurally invalid spec → 422.
         *     ``async`` + ``run_in_threadpool`` (blocking display_name resolution off the
         *     event loop), mirroring ``/validate``.
         */
        post: operations["order_project_api_project_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Project
         * @description Validate a ``project_data.json``. Returns 200 with the concatenated
         *     structural ⧺ block ⧺ semantic issue list + the derived ``ok`` flag; a 4xx is
         *     reserved for a malformed REQUEST (``read_raw_json_object`` / the body cap).
         *
         *     This is the SEMANTIC validator (reg_meta-backed). It now ALSO runs the
         *     build-time cross-block referential checks (orphan ``binding_options`` keys /
         *     suppress_k-on-non-categorical) — that half of the old ``/validate``↔``/bundle``
         *     divergence is CLOSED. The ONLY residual gap: ``/bundle`` additionally runs the
         *     step-4 capability gates (e.g. a build-required ``display_name``), which
         *     ``/validate`` does NOT — so a spec ``/validate`` greenlights can still 422 at
         *     ``/bundle`` on a capability gate (an intentional lenient residual: ``/validate``
         *     defaults ``display_name`` from reg_meta).
         *
         *     ``async`` only to read the body off the wire; the BLOCKING work (the structural
         *     parse + the semantic layer's per-binding sqlite resolution) is offloaded to the
         *     threadpool via ``run_in_threadpool`` so it never stalls the event loop (the
         *     catalog routes are plain ``def`` for the same reason). The reg_meta connection
         *     opens on that threadpool thread (one thread → the cross-thread sqlite P1 can't
         *     recur).
         */
        post: operations["validate_project_api_project_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search
         * @description Search registers, variables (concept-folded, #322), classifications, and
         *     codes/values (#352) over the shipped FTS indexes. Each group is an independent
         *     reg_meta `search()` call (register/variable/classification via the FTS
         *     `field="description"` path; codes via the `field="value"` path) so each carries
         *     its own `total_count` and per-group `limit`. A query with no usable token
         *     returns the selected group(s) empty (total 0) — not a 422.
         *
         *     ``?type=`` (#393 item 1) scopes the search: ``all`` (the default) preserves the
         *     four-group register→variable→classification→code behavior; any single type runs
         *     AND emits only that one group. Group ORDER is fixed for the ``all`` case.
         */
        get: operations["get_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BindingChild
         * @description A binding child under a register node — a thin (fqid, name) entry, NOT
         *     the embedded longitudinal record (that is only on the binding LEAF response).
         *     `coverage` (#351) is the per-variable study-window aggregate.
         */
        BindingChild: {
            coverage?: components["schemas"]["VariableCoverageModel"] | null;
            /** Fqid */
            fqid: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "binding";
            /** Name */
            name?: string | null;
        };
        /**
         * BindingNode
         * @description A binding LEAF (3-seg FQID) — the addressable variable plus its FULL
         *     longitudinal record embedded from one `Catalog.resolve` call: shared
         *     metadata, every state (each tagged with its variant), and the variable-grain
         *     `same_as` / `replaced_by` / `related_to` / `lineage` edges.
         *
         *     `lineage_warnings` are intentionally OMITTED — `ResolvedVariable` doesn't
         *     carry them; they arrive via A5.2's `/lineage_warnings` endpoint. This full-node
         *     shape is the binding leaf with NO narrowing query: a `?period` resolves via
         *     `resolve_at` (→ `StatesResponse`) instead, and a narrowing modifier (`?variant`
         *     / `?value_set_version`) WITHOUT `?period` is a 422 — it is inert without a
         *     period, so it errors rather than silently embedding full history.
         */
        BindingNode: {
            /** Definition */
            definition: string | null;
            /** Description */
            description: string | null;
            /** Fqid */
            fqid: string;
            /** Is Identifier */
            is_identifier: boolean;
            /** Is Sensitive */
            is_sensitive: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "binding";
            /** Lineage */
            lineage: components["schemas"]["LineageEdgeModel"][];
            /** Measurement Unit */
            measurement_unit: string | null;
            /** Name */
            name: string | null;
            /** Register Id */
            register_id: number;
            /** Related To */
            related_to: components["schemas"]["RelatedRefModel"][];
            /** Replaced By */
            replaced_by: components["schemas"]["VariableRefModel"][];
            /** Same As */
            same_as: components["schemas"]["VariableRefModel"][];
            /** Source Register Id */
            source_register_id: number | null;
            /** Source Register Text */
            source_register_text: string | null;
            /** States */
            states: components["schemas"]["VariableStateModel"][];
            /** Variable Id */
            variable_id: number;
            /** Via Same As */
            via_same_as?: string[] | null;
        };
        /**
         * CatalogDriftWarning
         * @description One boot-time steward-catalog drift warning.
         *
         *     Emitted when the steward's committed ``steward.project_data.json`` references
         *     an FQID reg_meta no longer admits: the steward-mode semantic validator
         *     downgrades the miss to a warning, the binding drops from the in-memory index,
         *     and this carries the warning to the SPA so it can show a "catalog drift"
         *     banner. ``code`` is the ValidationIssue code (``fqid_unresolved`` /
         *     ``value_set_missing`` / ``period_outside_state_validity``); ``path`` is the
         *     JSON pointer into the steward catalog. Always empty for the ``global``
         *     deployment (no filter).
         */
        CatalogDriftWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /**
         * ClassificationChainEdition
         * @description One edition in a classification's FULL succession timeline (#571), as
         *     embedded on `ClassificationNode.edition_chain`. The browse panel renders the
         *     whole chain (oldest first, terminal last) synchronously from these — no
         *     per-neighbor fetch.
         *
         *     `slug` is the load-bearing identity. Every chain edition is a LIVE
         *     `classification` row — the build validator guarantees succession editions are
         *     live (it fails on any `classification_replaced_by` edge whose endpoint has no
         *     live row), so `fqid` is None only when the slug is malformed/unresolvable (the
         *     SPA renders such an edition as plain text, not a link). `effective_year` is the
         *     year on the succession edge that names this edition as the successor (None for
         *     the terminal). `is_current` flags the terminal (current) edition; `is_self`
         *     flags the edition the caller queried (resolved to its canonical live slug when
         *     the query was a `same_as` alias). A dedicated model (NOT the search
         *     `ClassificationEditionModel`, which has no is_current/is_self) keeps the search
         *     edition a clean 4-field shape.
         */
        ClassificationChainEdition: {
            /**
             * Effective Year
             * @description The year on the succession edge naming this edition as the successor; None for the terminal (head) edition.
             */
            effective_year: number | null;
            /**
             * Fqid
             * @description The edition's 2-seg classification FQID, or None only when the slug is malformed/unresolvable (the build validator guarantees succession editions are live classification rows; rendered as plain text, not a link).
             */
            fqid: string | null;
            /**
             * Is Current
             * @description True for the terminal (current) edition — no outbound successor.
             */
            is_current: boolean;
            /**
             * Is Self
             * @description True for the edition the caller queried (resolved to its canonical live slug when the query was a same_as alias).
             */
            is_self: boolean;
            /**
             * Name
             * @description The edition's display name (every chain edition is a live row).
             */
            name: string | null;
            /**
             * Slug
             * @description The edition's literal slug (e.g. 'sun2000').
             */
            slug: string;
        };
        /**
         * ClassificationEditionModel
         * @description One edition of a folded classification succession chain (#571): a vintage
         *     of the same classification (e.g. `sun1996`, `sun2000`). Carried by
         *     `ClassificationSuccessionSearchResult.editions`, terminal-first then descending
         *     `effective_year`. Every edition is a live `classification` row (the build
         *     validator guarantees succession editions are live), so `fqid` is None only when
         *     the slug is malformed/unresolvable.
         */
        ClassificationEditionModel: {
            /**
             * Effective Year
             * @description The edition's effective year; None for the terminal (head) edition, which carries no successor-side year.
             */
            effective_year?: number | null;
            /**
             * Fqid
             * @description The edition's 2-seg classification FQID, None only when the slug is malformed/unresolvable (succession editions are live rows).
             */
            fqid?: string | null;
            /**
             * Name
             * @description The edition's display name, None when un-hydrated.
             */
            name?: string | null;
            /**
             * Slug
             * @description The edition's literal slug (e.g. 'sun2000').
             */
            slug: string;
        };
        /**
         * ClassificationNode
         * @description A classification leaf (`class/<slug>`, 2 seg).
         */
        ClassificationNode: {
            /** Edition Chain */
            edition_chain?: components["schemas"]["ClassificationChainEdition"][];
            /** Fqid */
            fqid: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "classification";
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Via Same As */
            via_same_as?: string[] | null;
        };
        /**
         * ClassificationRootNode
         * @description The classification-root sentinel (`class`, 1 seg) — a child of the root
         *     and a resolvable node whose `children` are every classification (see
         *     reg_meta/DESIGN.md → FQID grammar: `class` is a reserved slug, not a real
         *     provider).
         */
        ClassificationRootNode: {
            /**
             * Fqid
             * @default class
             */
            fqid: string;
            /**
             * Kind
             * @default classification-root
             * @constant
             */
            kind: "classification-root";
            /**
             * Name
             * @default Classifications
             */
            name: string;
        };
        /**
         * ClassificationRootResponse
         * @description `GET /api/catalog/class` — the classification-root + every classification
         *     as children, plus the derived vintage `groups` (#303; grouped
         *     classifications ALSO appear in `children`).
         */
        ClassificationRootResponse: {
            /** Children */
            children: components["schemas"]["ClassificationNode"][];
            /**
             * Fqid
             * @default class
             */
            fqid: string;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["ConceptGroupModel"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "classification-root";
            /**
             * Name
             * @default Classifications
             */
            name: string;
        };
        /**
         * ClassificationSearchGroup
         * @description The `classifications` result group: leaf hits ⧺ folded classification
         *     succession rows (#571, edition chains) ⧺ folded umbrella concept-group rows
         *     (#516, e.g. `group:sun`).
         */
        ClassificationSearchGroup: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            group: "classifications";
            /** Results */
            results: (components["schemas"]["ClassificationSearchResult"] | components["schemas"]["ClassificationSuccessionSearchResult"] | components["schemas"]["ConceptGroupSearchResult"])[];
            /** Total Count */
            total_count: number;
        };
        /**
         * ClassificationSearchResult
         * @description A classification hit (`classification_fts` short_name/name/name_en/
         *     description — #350 activates this previously-unsearched index). When the hit
         *     is a LONE member of a vintage group (the family didn't fold because only one
         *     member matched), `concept_group`/`concept_group_label` annotate the family so
         *     it stays discoverable — symmetric with `VariableSearchResult`; both None
         *     otherwise.
         */
        ClassificationSearchResult: {
            /** Concept Group */
            concept_group?: string | null;
            /** Concept Group Label */
            concept_group_label?: string | null;
            /** Fqid */
            fqid: string | null;
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /**
             * Terminal Fqid
             * @description When this is a non-current edition that the query hit alone, the fqid of the current/terminal edition in its succession chain (#571) — lets the UI link to the current edition; None for a current edition or a non-edition classification.
             */
            terminal_fqid?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "classification";
        };
        /**
         * ClassificationSuccessionSearchResult
         * @description A folded classification-succession row (#571): a query hit ≥2 distinct
         *     editions of one classification chain (the vintages, e.g. SUN 1996/2000), so they
         *     collapse to a single result keyed on the TERMINAL (current) edition. `editions`
         *     is the full chain (terminal-first, descending year) so the SPA can render "this
         *     classification has editions …"; `matched_count` is how many editions the query
         *     actually hit. A succession row is NOT itself a concept group — the terminal
         *     `fqid` is the navigable target.
         */
        ClassificationSuccessionSearchResult: {
            /**
             * Editions
             * @description The full edition chain, terminal-first then descending year.
             */
            editions?: components["schemas"]["ClassificationEditionModel"][];
            /**
             * Fqid
             * @description The terminal (current) edition's classification FQID — the navigable target. None only when the slug is malformed/unresolvable (the terminal is always a live classification row).
             */
            fqid: string | null;
            /**
             * Matched Count
             * @description How many editions in the chain the query hit.
             * @default 0
             */
            matched_count: number;
            /**
             * Name
             * @description The terminal edition's display name.
             */
            name?: string | null;
            /**
             * Short Name
             * @description The terminal edition's short name (e.g. 'SUN').
             */
            short_name?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "classification_succession";
        };
        /**
         * CodeOwnerClassification
         * @description A classification that carries a code (#352) — catalog-scoped (no owning
         *     register).
         */
        CodeOwnerClassification: {
            /** Fqid */
            fqid: string | null;
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
        };
        /**
         * CodeOwnerVariable
         * @description A variable that carries a code (#352). `register` is the owning register's
         *     display name (context for the omnibox); the Python attr is `register_name` to
         *     avoid the `BaseModel.register` method shadow (see `VariableRefModel`).
         */
        CodeOwnerVariable: {
            /** Fqid */
            fqid: string | null;
            /** Name */
            name?: string | null;
            /** Register */
            register?: string | null;
        };
        /**
         * CodeSearchGroup
         * @description The `codes` result group (#352). `total_count` is the result count before
         *     the per-group display limit (so the SPA can show "showing N of M").
         */
        CodeSearchGroup: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            group: "codes";
            /** Results */
            results: components["schemas"]["CodeSearchResult"][];
            /** Total Count */
            total_count: number;
        };
        /**
         * CodeSearchResult
         * @description A code/value hit (`value_code_fts` label match + code-shape match, #352).
         *     `code`/`label` are the SCB value pair; `variables`/`classifications` are a
         *     bounded representative slice of the owning entities (the researcher's actual
         *     target), and `variable_count`/`classification_count` are the full totals before
         *     the slice cap.
         */
        CodeSearchResult: {
            /**
             * Classification Count
             * @default 0
             */
            classification_count: number;
            /**
             * Classifications
             * @default []
             */
            classifications: components["schemas"]["CodeOwnerClassification"][];
            /** Code */
            code: string;
            /** Code System */
            code_system?: string | null;
            /** Label */
            label: string;
            /**
             * Type
             * @default code
             * @constant
             */
            type: "code";
            /**
             * Variable Count
             * @default 0
             */
            variable_count: number;
            /**
             * Variables
             * @default []
             */
            variables: components["schemas"]["CodeOwnerVariable"][];
        };
        /**
         * ConceptGroupMemberModel
         * @description A group member: the leaf's real FQID (binding or `class/<slug>`), its
         *     display name, and its facet assignments (empty on edge-group members).
         */
        ConceptGroupMemberModel: {
            /** Facets */
            facets: components["schemas"]["GroupFacetModel"][];
            /** Fqid */
            fqid: string;
            /** Name */
            name?: string | null;
        };
        /**
         * ConceptGroupModel
         * @description One derived concept group. `key` is the scope-unique derivation key (a
         *     UI anchor, not an FQID); `source` records the derivation dimension; `axes`
         *     are the sorted facet axes the members carry (empty for edge groups);
         *     members are ordered by facet values along `axes`, then slug.
         */
        ConceptGroupModel: {
            /** Axes */
            axes: string[];
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Members */
            members: components["schemas"]["ConceptGroupMemberModel"][];
            /**
             * Source
             * @enum {string}
             */
            source: "edge" | "token" | "curated";
        };
        /**
         * ConceptGroupSearchResult
         * @description A folded concept-group row (#322): ≥2 sibling members matched OR the
         *     group's own label matched, so the family collapses to one result. `kind` is
         *     'variable' or 'classification' (which group bucket it belongs to);
         *     `member_count` is the family's full size, `matched_count` how many members
         *     the query hit, `label_matched` whether the group label/key matched directly.
         *     `members` is the full facet-ordered member list (each a real leaf FQID) so
         *     the SPA can expand the family inline — a group is NOT itself FQID-addressable.
         */
        ConceptGroupSearchResult: {
            /** Group Key */
            group_key: string;
            /** Group Label */
            group_label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "variable" | "classification";
            /**
             * Label Matched
             * @default false
             */
            label_matched: boolean;
            /**
             * Matched Count
             * @default 0
             */
            matched_count: number;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["ConceptGroupMemberModel"][];
            /** Register */
            register?: string | null;
            /** Source */
            source?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group";
        };
        /**
         * ContextResponse
         * @description ``GET /api/context`` — deployment identity, branding, build info.
         *
         *     No git sha (decision: no new provenance dep). The reg_meta block reflects
         *     the DB the backend booted against; the webapp block reflects the installed
         *     packages. ``catalog_drift_warnings`` is the steward-catalog
         *     drift surfaced at boot — empty for ``global`` and for an up-to-date catalog.
         */
        ContextResponse: {
            /** Catalog Drift Warnings */
            catalog_drift_warnings?: components["schemas"]["CatalogDriftWarning"][];
            reg_meta: components["schemas"]["RegMetaInfo"];
            steward: components["schemas"]["StewardInfo"];
            webapp: components["schemas"]["WebappInfo"];
        };
        /**
         * DimensionsResponse
         * @description `GET /api/catalog/{fqid}/dimensions` (#489) — the concept-group
         *     dimension memberships containing this binding's variable (the
         *     'pick your variant' facet groups: level / population / rank / …). A
         *     `ConceptGroupModel` per containing group; empty when the variable is in
         *     no group.
         */
        DimensionsResponse: {
            /** Binding */
            binding: string;
            /** Dimensions */
            dimensions: components["schemas"]["ConceptGroupModel"][];
        };
        /**
         * DocDetail
         * @description `GET /api/docs/doc/{identifier}` — metadata + source pointer + a BOUNDED
         *     `excerpt` (never the full converted body). `source_url` is the resolved SCB
         *     PDF link (curated source→PDF map applied at doc-DB build, #372), None when
         *     uncurated; `source_title` is the human-readable publication title for that
         *     source. `register` is the wire key (Python attr `register_name`).
         */
        DocDetail: {
            /** Display Name */
            display_name?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Filename */
            filename: string;
            /**
             * Kind
             * @default doc
             * @constant
             */
            kind: "doc";
            /** Register */
            register?: string | null;
            /** Source */
            source?: string | null;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Variable */
            variable?: string | null;
        };
        /**
         * DocResult
         * @description One documentation hit. `snippet` is a query-context EXCERPT (the FTS5
         *     snippet), not full text. `source` is the SCB source-document identifier the
         *     doc was derived from; `source_url` is the resolved SCB PDF link (a curated
         *     source→PDF map applied at doc-DB build, #372), None when the source is
         *     uncurated; `source_title` is the human-readable publication title for that
         *     source (also None when uncurated). `fuzzy` marks a name/provider_key match
         *     (the "mentioned in documentation" variable hook) as a heuristic text match,
         *     not an authoritative variable→doc link. `register` is the wire key; the
         *     Python attr is `register_name` (avoids the `BaseModel.register` shadow).
         */
        DocResult: {
            /** Display Name */
            display_name?: string | null;
            /** Filename */
            filename: string;
            /**
             * Fuzzy
             * @default false
             */
            fuzzy: boolean;
            /** Register */
            register?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Source */
            source?: string | null;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Variable */
            variable?: string | null;
        };
        /**
         * DocSearchResponse
         * @description `GET /api/docs/search`. `ingested` is False when the deployment ships no
         *     docs index at all (`reg_meta_docs.db` absent) — "no docs ingested", distinct
         *     from an empty `results` for a real query against a present index.
         */
        DocSearchResponse: {
            /** Ingested */
            ingested: boolean;
            /**
             * Kind
             * @default doc-search
             * @constant
             */
            kind: "doc-search";
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["DocResult"][];
            /** Total Count */
            total_count: number;
        };
        /**
         * DocVariableMentions
         * @description `GET /api/docs/for-variable` — the "mentioned in documentation" hook for a
         *     variable leaf. `ingested` is whether the docs index exists at all;
         *     `register_ingested` whether THIS register has any ingested docs — absence
         *     means "no docs ingested for this register" (coverage is LISA-only), NOT "no
         *     documentation exists". `results` are FUZZY name/provider_key text matches
         *     (each `fuzzy=True`). `register` is the wire key (Python attr
         *     `register_name`).
         */
        DocVariableMentions: {
            /** Ingested */
            ingested: boolean;
            /**
             * Kind
             * @default doc-mentions
             * @constant
             */
            kind: "doc-mentions";
            /** Register */
            register?: string | null;
            /** Register Ingested */
            register_ingested: boolean;
            /** Results */
            results: components["schemas"]["DocResult"][];
            /** Total Count */
            total_count: number;
        };
        /**
         * GroupFacetModel
         * @description One facet assignment on a group member: `axis` names the dimension
         *     ('month' / 'rank' / 'vintage'), `value` sorts, `label` displays.
         */
        GroupFacetModel: {
            /** Axis */
            axis: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LineageEdgeModel
         * @description A consumer-side lineage edge (state grain — see reg_meta_build/DESIGN.md →
         *     Consumer-side lineage (variable_state_lineage)) tying a consumer state to
         *     a source state over their validity intersection. `source_fqid` is the source
         *     state's 3-seg binding FQID (None when the source slugs aren't populated).
         */
        LineageEdgeModel: {
            /** Consumer State Id */
            consumer_state_id: number;
            /** Source Fqid */
            source_fqid?: string | null;
            /** Source State Id */
            source_state_id: number;
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to: string;
        };
        /**
         * LineageResponse
         * @description `GET /api/catalog/{fqid}/lineage` — consumer-side lineage edges.
         *
         *     Maps what `reg_meta.LineageEdge` carries (consumer/source state ids, the
         *     validity intersection, source_fqid). The richer per-source-state shape
         *     (embedding each source state's variant / value_set / column) is a possible
         *     reg_meta enhancement, NOT blocked on here — see DESIGN.md.
         */
        LineageResponse: {
            /** Binding */
            binding: string;
            /** Lineage Edges */
            lineage_edges: components["schemas"]["LineageEdgeModel"][];
        };
        /**
         * LineageWarningModel
         * @description A build-time lineage warning for a consumer state:
         *     `variable_state_lineage_warning`. `warning_kind` is `no_source_state` or
         *     `ambiguous_source_variant`. Maps 1:1 to `reg_meta.catalog.LineageWarning`.
         */
        LineageWarningModel: {
            /** Consumer State Id */
            consumer_state_id: number;
            /** Message */
            message: string;
            /** Warning Kind */
            warning_kind: string;
        };
        /**
         * LineageWarningsResponse
         * @description `GET /api/catalog/{fqid}/lineage_warnings` — build-time lineage warnings.
         *     Empty list when lineage resolved cleanly.
         */
        LineageWarningsResponse: {
            /** Binding */
            binding: string;
            /** Lineage Warnings */
            lineage_warnings: components["schemas"]["LineageWarningModel"][];
        };
        /**
         * PredecessorsResponse
         * @description `GET /api/catalog/{fqid}/predecessors` — inbound succession.
         */
        PredecessorsResponse: {
            /** Binding */
            binding: string;
            /** Predecessors */
            predecessors: components["schemas"]["VariableRefModel"][];
        };
        /**
         * ProviderNode
         * @description A provider node (1-seg FQID, e.g. `scb`). A child of the root and a
         *     resolvable node (its `children` are the provider's registers).
         */
        ProviderNode: {
            /** Fqid */
            fqid: string;
            /**
             * Kind
             * @default provider
             * @constant
             */
            kind: "provider";
            /** Name */
            name?: string | null;
        };
        /**
         * ProviderResponse
         * @description `GET /api/catalog/{provider}` — the provider + its registers as children.
         */
        ProviderResponse: {
            /** Children */
            children: components["schemas"]["RegisterNode"][];
            /** Fqid */
            fqid: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "provider";
            /** Name */
            name?: string | null;
        };
        /**
         * RegMetaInfo
         * @description reg_meta build provenance, read from the DB ``import_manifest``.
         */
        RegMetaInfo: {
            /**
             * Import Date
             * @description UTC timestamp the reg_meta DB was built/imported.
             */
            import_date: string;
            /**
             * Schema Version
             * @description Schema version of the reg_meta DB build (e.g. '5.2.0').
             */
            schema_version: string;
        };
        /**
         * RegisterCoverageModel
         * @description Per-register coverage: `variable_count` slugged variables + the span over
         *     all their states.
         */
        RegisterCoverageModel: {
            /** Coverage From */
            coverage_from?: string | null;
            /** Coverage To */
            coverage_to?: string | null;
            /**
             * Open Ended
             * @default false
             */
            open_ended: boolean;
            /**
             * Variable Count
             * @default 0
             */
            variable_count: number;
        };
        /**
         * RegisterNode
         * @description A register node (2-seg FQID, e.g. `scb/lisa`). Its `children` are the
         *     register's bindings; `variants` is a forward-declared reference stub for
         *     A5.2's variant browser (a link, not data). `coverage` (#351) is populated
         *     when the node is a PROVIDER child (the register listing); None on the
         *     register's own node.
         */
        RegisterNode: {
            coverage?: components["schemas"]["RegisterCoverageModel"] | null;
            /** Fqid */
            fqid: string;
            /**
             * Kind
             * @default register
             * @constant
             */
            kind: "register";
            /** Name */
            name?: string | null;
            /** Purpose */
            purpose?: string | null;
        };
        /**
         * RegisterResponse
         * @description `GET /api/catalog/{provider}/{register}` — the register + its bindings and
         *     the variant-browser reference stub as children, plus the derived concept
         *     `groups` (#303; grouped bindings ALSO appear in `children` — the flat list
         *     stays complete, the SPA folds it).
         */
        RegisterResponse: {
            /** Children */
            children: (components["schemas"]["BindingChild"] | components["schemas"]["VariantsRef"])[];
            coverage?: components["schemas"]["RegisterCoverageModel"] | null;
            /** Fqid */
            fqid: string;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["ConceptGroupModel"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "register";
            /** Name */
            name?: string | null;
            /** Purpose */
            purpose?: string | null;
        };
        /**
         * RegisterSearchGroup
         * @description The `registers` result group. `total_count` is the folded result count
         *     for this group BEFORE the per-group display limit (so the SPA can show
         *     "showing N of M").
         */
        RegisterSearchGroup: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            group: "registers";
            /** Results */
            results: components["schemas"]["RegisterSearchResult"][];
            /** Total Count */
            total_count: number;
        };
        /**
         * RegisterSearchResult
         * @description A register hit (`register_fts` name/purpose).
         */
        RegisterSearchResult: {
            /** Fqid */
            fqid: string | null;
            /** Name */
            name?: string | null;
            /** Purpose */
            purpose?: string | null;
            /**
             * Type
             * @default register
             * @constant
             */
            type: "register";
        };
        /**
         * RelatedRefModel
         * @description A split-sibling edge (`variable_related_to` — see reg_meta_build/DESIGN.md →
         *     Build-time triage (SCB)) with its
         *     `relation_kind`. `register` is the alias for `register_name` (see
         *     `VariableRefModel`) — avoids the `BaseModel.register` method shadow.
         */
        RelatedRefModel: {
            /** Fqid */
            fqid: string | null;
            /** Provider */
            provider: string;
            /** Register */
            register: string;
            /** Relation Kind */
            relation_kind: string;
            /** Variable */
            variable: string;
        };
        /**
         * RelatedResponse
         * @description `GET /api/catalog/{fqid}/related` — split-sibling edges.
         */
        RelatedResponse: {
            /** Binding */
            binding: string;
            /** Related */
            related: components["schemas"]["RelatedRefModel"][];
        };
        /**
         * RootResponse
         * @description `GET /api/catalog` — the catalog root: every provider plus the
         *     classification-root sentinel.
         */
        RootResponse: {
            /** Children */
            children: (components["schemas"]["ProviderNode"] | components["schemas"]["ClassificationRootNode"])[];
            /**
             * Kind
             * @default root
             * @constant
             */
            kind: "root";
        };
        /**
         * SearchResponse
         * @description `GET /api/search?q=` — typed result groups over the shipped FTS indexes.
         *     `query` echoes the raw user query; `groups` is the ordered list of typed
         *     groups (see the `SearchGroup` union for the extension contract).
         */
        SearchResponse: {
            /** Groups */
            groups: (components["schemas"]["RegisterSearchGroup"] | components["schemas"]["VariableSearchGroup"] | components["schemas"]["ClassificationSearchGroup"] | components["schemas"]["CodeSearchGroup"])[];
            /**
             * Kind
             * @default search
             * @constant
             */
            kind: "search";
            /** Query */
            query: string;
        };
        /**
         * StatesResponse
         * @description `GET /api/catalog/{fqid}/states` — the binding's full state history.
         *     Same `states` shape the binding leaf embeds, as a standalone envelope. With a
         *     `?period` query on the catch-all this same shape carries the resolve_at
         *     subset (uniform: codegen sees one state-list type).
         */
        StatesResponse: {
            /** Binding */
            binding: string;
            /** States */
            states: components["schemas"]["VariableStateModel"][];
        };
        /**
         * StewardInfo
         * @description Deployment identity + branding, from ``steward.toml``.
         */
        StewardInfo: {
            /** Id */
            id: string;
            /** Long Name */
            long_name: string;
            /** Name */
            name: string;
        };
        /**
         * SuccessorsResponse
         * @description `GET /api/catalog/{fqid}/successors` — outbound succession.
         */
        SuccessorsResponse: {
            /** Binding */
            binding: string;
            /** Successors */
            successors: components["schemas"]["VariableRefModel"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationIssueModel
         * @description One validation issue — a 1:1 Pydantic wrapper of reg_schema's frozen
         *     ``ValidationIssue`` dataclass. ``level`` is the tri-state severity; ``path`` is
         *     an RFC-6901 JSON pointer into ``project_data.json`` (empty for whole-document
         *     issues); ``code`` is the stable, namespaced rule identifier the SPA maps to a
         *     UI affordance.
         */
        ValidationIssueModel: {
            /** Code */
            code: string;
            /**
             * Level
             * @enum {string}
             */
            level: "error" | "warning" | "info";
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /**
         * ValidationResultModel
         * @description `POST /api/project/validate` response — the concatenated issue list
         *     (structural ⧺ block ⧺ semantic) plus the derived ``ok`` flag.
         *
         *     ``ok`` mirrors ``reg_schema.ValidationResult.ok``: True iff NO error-level
         *     issue is present (warnings/info do not flip it). A validation FAILURE is a
         *     SUCCESSFUL validation RESPONSE — this carries HTTP 200 with ``ok=false`` and
         *     the issues; 4xx is reserved for a malformed request (bad JSON / oversized body
         *     / wrong content-type), never for a spec that simply failed to validate.
         */
        ValidationResultModel: {
            /** Issues */
            issues: components["schemas"]["ValidationIssueModel"][];
            /** Ok */
            ok: boolean;
        };
        /**
         * ValueSetMember
         * @description One (code, label) pair of a state's value set.
         */
        ValueSetMember: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /**
         * VariableCoverageModel
         * @description Per-variable coverage over its `variable_state` windows.
         */
        VariableCoverageModel: {
            /** Coverage From */
            coverage_from?: string | null;
            /** Coverage To */
            coverage_to?: string | null;
            /**
             * Open Ended
             * @default false
             */
            open_ended: boolean;
            /**
             * State Count
             * @default 0
             */
            state_count: number;
        };
        /**
         * VariableRefModel
         * @description A variable-grain edge endpoint (`same_as` / succession). `fqid` is the
         *     neighbor's 3-seg binding FQID (None when its slug isn't populated); the
         *     `provider`/`register`/`variable` triple is the load-bearing identity when
         *     `fqid` is None. `reason` / `effective_year` are succession-only (#142), None
         *     on `same_as`.
         *
         *     The Python attribute is `register_name` because a bare `register` field
         *     shadows `BaseModel.register` (a Pydantic v2 method) and warns; the wire/JSON
         *     key stays `register` via the alias (the alias is also the canonical init
         *     param — the mapper constructs with `register=`). FastAPI serializes by alias
         *     by default, so the response key is `register`.
         */
        VariableRefModel: {
            /** Effective Year */
            effective_year?: number | null;
            /** Fqid */
            fqid: string | null;
            /** Provider */
            provider: string;
            /** Reason */
            reason?: string | null;
            /** Register */
            register: string;
            /** Variable */
            variable: string;
        };
        /**
         * VariableSearchGroup
         * @description The `variables` result group (leaf hits ⧺ folded concept groups).
         */
        VariableSearchGroup: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            group: "variables";
            /** Results */
            results: (components["schemas"]["VariableSearchResult"] | components["schemas"]["ConceptGroupSearchResult"])[];
            /** Total Count */
            total_count: number;
        };
        /**
         * VariableSearchResult
         * @description A variable hit (`variable_fts` name/definition/description). `register` is
         *     the owning register's display name (context for the omnibox). When the hit is
         *     a LONE member of a concept group (#322 — the family didn't fold because only
         *     one member matched), `concept_group`/`concept_group_label` annotate the
         *     family so it stays discoverable; both None otherwise.
         */
        VariableSearchResult: {
            /** Concept Group */
            concept_group?: string | null;
            /** Concept Group Label */
            concept_group_label?: string | null;
            /** Definition */
            definition?: string | null;
            /** Fqid */
            fqid: string | null;
            /** Name */
            name?: string | null;
            /** Register */
            register?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "variable";
        };
        /**
         * VariableStateModel
         * @description One `variable_state` row — a per-delivery shape tagged with its variant
         *     coordinate (see reg_meta/DESIGN.md → Two-level variable model). `value_set` is
         *     the hydrated (code, label) pairs, None when
         *     the state carries no value set.
         */
        VariableStateModel: {
            /** Classification Slug */
            classification_slug: string | null;
            /** Data Length */
            data_length: string | null;
            /** Data Type */
            data_type: string | null;
            /** Delivery Column Name */
            delivery_column_name: string | null;
            /** Is Identifier */
            is_identifier: boolean;
            /** Period Token */
            period_token?: string | null;
            /** Register Variant Id */
            register_variant_id: number;
            /** State Id */
            state_id: number;
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to: string;
            /** Value Set */
            value_set: components["schemas"]["ValueSetMember"][] | null;
            /** Value Set Id */
            value_set_id: number | null;
            /** Value Set Version Label */
            value_set_version_label: string;
            /** Variant */
            variant: string;
        };
        /**
         * VariantModel
         * @description One register variant (the `register_variant` sub-resource) — the
         *     `?variant=` browse axis. A variant is NOT FQID-addressable (the variant left
         *     the binding FQID — see reg_meta/DESIGN.md → Two-level variable model), so it
         *     carries the variant `slug` (the browse coordinate) + display fields, not an
         *     `Fqid`. Maps 1:1 to
         *     `reg_meta.catalog.VariantSummary`. A4.4c adds the read-only `panel_*`
         *     fields: `panel_entity_key` is a bare variable-slug string or a list of slugs
         *     (composite); `panel_time_key` is "period", a variable-slug, or a list of
         *     slugs (composite); `panel_time_grain` is 'delivery'/'row'. Most variants
         *     carry no panel data → all three are None.
         */
        VariantModel: {
            /** Description */
            description?: string | null;
            /** Display Group */
            display_group?: string | null;
            /** Name */
            name?: string | null;
            /** Panel Entity Key */
            panel_entity_key?: string | string[] | null;
            /** Panel Time Grain */
            panel_time_grain?: string | null;
            /** Panel Time Key */
            panel_time_key?: string | string[] | null;
            /** Slug */
            slug: string;
        };
        /**
         * VariantsRef
         * @description Reference to a register's variant browser — the `/{provider}/{register}/
         *     variants` sub-resource (wired in A5.2a). A discriminated slot in
         *     `RegisterChild` so the union / TS types carry the navigable `register_fqid`;
         *     the client GETs `{register_fqid}/variants` to list them.
         */
        VariantsRef: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "variants-ref";
            /** Register Fqid */
            register_fqid: string;
        };
        /**
         * VariantsResponse
         * @description `GET /api/catalog/{provider}/{register}/variants` — the variant browser.
         *     The wire key `register` is the 2-seg register FQID; `variants` the
         *     register's `register_variant` sub-resource list.
         *
         *     The Python attr is `register_name` (aliased to `register`) for the same reason
         *     as `VariableRefModel`: a bare `register` field shadows `BaseModel.register` (a
         *     Pydantic v2 method) and warns. FastAPI serializes by alias, so the wire key
         *     stays `register`; the alias is also the canonical init param.
         */
        VariantsResponse: {
            /** Register */
            register: string;
            /** Variants */
            variants: components["schemas"]["VariantModel"][];
        };
        /**
         * WebappInfo
         * @description Package versions for the deployed backend + its reg_meta dependency.
         */
        WebappInfo: {
            /**
             * Reg Meta Version
             * @description Installed reg_meta package version — distinct from reg_meta.schema_version, which is the DB build.
             */
            reg_meta_version: string;
            /**
             * Version
             * @description Installed reg_webapp package version.
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    build_mona_bundle_api_bundle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
        };
    };
    get_catalog_root_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    get_catalog_node_api_catalog__fqid__get: {
        parameters: {
            query?: {
                period?: string | null;
                variant?: string | null;
                value_set_version?: string | null;
            };
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["ProviderResponse"] | components["schemas"]["RegisterResponse"] | components["schemas"]["BindingNode"] | components["schemas"]["ClassificationRootResponse"] | components["schemas"]["ClassificationNode"]) | components["schemas"]["StatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binding_dimensions_api_catalog__fqid__dimensions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DimensionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binding_lineage_api_catalog__fqid__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binding_lineage_warnings_api_catalog__fqid__lineage_warnings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageWarningsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binding_predecessors_api_catalog__fqid__predecessors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredecessorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binding_related_api_catalog__fqid__related_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binding_states_api_catalog__fqid__states_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_binding_successors_api_catalog__fqid__successors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fqid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_register_variants_api_catalog__provider___register__variants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                register: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_context_api_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
        };
    };
    get_doc_api_docs_doc__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_docs_for_variable_api_docs_for_variable_get: {
        parameters: {
            query: {
                q: string;
                register?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocVariableMentions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_docs_search_api_docs_search_get: {
        parameters: {
            query: {
                offset?: number;
                q: string;
                register?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_kit_api_kit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
        };
    };
    order_project_api_project_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
        };
    };
    validate_project_api_project_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResultModel"];
                };
            };
        };
    };
    get_search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
