/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context */
        get: operations["get_context_api_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContextResponse
         * @description ``GET /api/context`` — deployment identity, branding, build info (§9.5).
         *
         *     No git sha (decision: no new provenance dep). The reg_meta block reflects
         *     the DB the backend booted against; the webapp block reflects the installed
         *     packages.
         */
        ContextResponse: {
            reg_meta: components["schemas"]["RegMetaInfo"];
            steward: components["schemas"]["StewardInfo"];
            webapp: components["schemas"]["WebappInfo"];
        };
        /**
         * RegMetaInfo
         * @description reg_meta build provenance, read from the DB ``import_manifest``.
         */
        RegMetaInfo: {
            /**
             * Import Date
             * @description UTC timestamp the reg_meta DB was built/imported.
             */
            import_date: string;
            /**
             * Schema Version
             * @description Schema version of the reg_meta DB build (e.g. '5.1.0').
             */
            schema_version: string;
        };
        /**
         * StewardInfo
         * @description Deployment identity + branding, from ``steward.toml`` (§9.1).
         */
        StewardInfo: {
            /** Id */
            id: string;
            /** Long Name */
            long_name: string;
            /** Name */
            name: string;
        };
        /**
         * WebappInfo
         * @description Package versions for the deployed backend + its reg_meta dependency.
         */
        WebappInfo: {
            /**
             * Reg Meta Version
             * @description Installed reg_meta package version — distinct from reg_meta.schema_version, which is the DB build.
             */
            reg_meta_version: string;
            /**
             * Version
             * @description Installed reg_webapp package version.
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_context_api_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
        };
    };
}
