/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/project/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Order Project
         * @description Materialize a ``project_data.json`` into the JSON order manifest.
         *
         *     A THIN adapter over ``reg_meta.order.materialize_order`` (reg_meta/DESIGN.md → Order
         *     materializer and manifest): no gate, no fallback and no rendering lives here, so
         *     this endpoint and the ``reg-meta order`` CLI emit byte-identical manifests. The
         *     selected artifact determines orderability: catalog artifacts use global fallback;
         *     steward artifacts use their compiled holdings and steward identity.
         *
         *     200 is the manifest — ``application/json``, downloaded as ``order.json``.
         *     Anything else is NOT AN ORDER: 422 either because the spec is invalid
         *     (``project_from_raw``) or because the materializer blocked it, carrying the
         *     typed ``OrderBlockedModel`` — the findings as DATA (each with its code and
         *     its source/variable/period coordinates), not one flattened line. There is
         *     deliberately no partial 200.
         *
         *     ``async`` + ``run_in_threadpool`` (blocking sqlite resolution off the event
         *     loop), mirroring ``/validate``.
         */
        post: operations["order_project_api_project_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Project
         * @description Validate a ``project_data.json``. Returns 200 with the concatenated
         *     structural ⧺ semantic issue list + the derived ``ok`` flag; a 4xx is
         *     reserved for a malformed REQUEST (``read_raw_json_object`` / the body cap).
         *
         *     A THIN adapter over reg_meta's ``semantic.validate_project`` (reg_meta/DESIGN.md →
         *     Project semantic validation): the composition, every issue and the serialization
         *     live there, so this endpoint and ``reg-meta validate`` emit byte-identical findings.
         *     The 200 body is ``semantic.validation_json`` VERBATIM, returned as a raw
         *     ``Response`` (FastAPI passes it through without re-serializing) while
         *     ``response_model=`` still publishes ``ValidationResultModel`` as the typed contract
         *     for the OpenAPI snapshot + the SPA codegen — the ``/order`` pattern.
         *
         *     ``async`` only to read the body off the wire; the BLOCKING work (the structural
         *     parse + the semantic layer's per-binding sqlite resolution) is offloaded to the
         *     threadpool via ``run_in_threadpool`` so it never stalls the event loop (the
         *     catalog routes are plain ``def`` for the same reason). The reg_meta connection
         *     opens on that threadpool thread (one thread → the cross-thread sqlite P1 can't
         *     recur).
         */
        post: operations["validate_project_api_project_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Binding
         * @description A binding on a Source — one variable to include in the extract.
         *
         *     ``variable`` is the binding FQID: ``<provider>/<register>/<slug>`` (3
         *     segments, see reg_meta/DESIGN.md → FQID grammar). Its ``provider/register`` prefix (first 2 segments) must
         *     equal the source's ``register_variant`` prefix — the variant is NOT
         *     repeated here, it lives once on the Source. That cross-field rule
         *     is enforced by the structural validator. There is no ``@version`` pin —
         *     that grammar is retired.
         *
         *     A FQID names one CONCEPT. The reg_meta build enforces one value set per
         *     ``(variable, variant, period, delivery_column)``, but a concept may carry
         *     several co-existing delivery columns — parallel REPRESENTATIONS of it (SSYK
         *     3/4/5-digit, age 5/10-yr brackets). ``representation`` selects which one (by
         *     its ``variable_alias.delivery_column_name``); it is required only when the
         *     concept resolves to >1 column at the source's ``(variant, period)`` — the
         *     semantic validator (see reg_meta/DESIGN.md → Project semantic validation (semantic.py)) flags an ambiguous binding that omits it, and the
         *     SPA offers a chooser. A single-representation concept leaves it ``None``.
         *
         *     ``display_name`` is optional: when absent, reg_meta-backed consumers
         *     resolve the default from ``variable_alias.delivery_column_name`` for
         *     the binding's state at the source's ``(register_variant, period)``. A
         *     reg_meta-free consumer that materializes data artifacts must resolve
         *     the default itself before emitting them — it never carries an
         *     unresolved ``display_name`` into its output.
         */
        Binding: {
            /**
             * Date Format
             * @default null
             */
            date_format: string | null;
            /**
             * Datetime Format
             * @default null
             */
            datetime_format: string | null;
            /**
             * Display Name
             * @default null
             */
            display_name: string | null;
            /**
             * Id Subtype
             * @default null
             */
            id_subtype: ("integer" | "string") | null;
            /**
             * Numeric Subtype
             * @default null
             */
            numeric_subtype: ("integer" | "double") | null;
            /**
             * Representation
             * @default null
             */
            representation: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "id" | "categorical" | "numeric" | "date" | "datetime" | "opaque";
            /**
             * Value Set
             * @default null
             */
            value_set: string | null;
            /** Variable */
            variable: string;
        };
        /**
         * ClipReport
         * @description One informational availability clip (reported, never silent, never
         *     an error): the binding asked for `requested_period` and is ordered for
         *     `ordered_period`, because that is where the column is documented as
         *     available. Emitted only when the clip actually narrows the request.
         */
        ClipReport: {
            /** Ordered Period */
            ordered_period: string;
            /** Requested Period */
            requested_period: string;
            /** Source */
            source: string;
            /** Variable */
            variable: string;
        };
        /**
         * LiteralPeriod
         * @description The ``{"period": int | string}`` time_key form.
         *
         *     The only way to express a string-shaped literal period at the
         *     schema level. Disambiguates ``"2018"`` (column ref) from
         *     ``{"period": "2018-01"}`` (literal period).
         */
        LiteralPeriod: {
            /** Period */
            period: number | string;
        };
        /**
         * LogicalCoordinate
         * @description What the researcher asked for: the project-side coordinate of one entry.
         *
         *     `variable` is the 3-segment binding FQID; `representation` is the canonical
         *     reg_meta `delivery_column_name` the slice resolved to — a join discriminator
         *     carried for provenance, NOT the output column (that is
         *     `PhysicalCoordinate.column`).
         *
         *     `register` is a `BaseModel` method, so the Python attr is `register_name`
         *     with a `"register"` alias — the wire key stays the order-contract coordinate
         *     spelling (same pattern as `catalog.BindingGroupRef`).
         */
        LogicalCoordinate: {
            /** Provider */
            provider: string;
            /** Register */
            register: string;
            /** Representation */
            representation: string;
            /** Variable */
            variable: string;
            /** Variant */
            variant: string;
        };
        /**
         * OrderBlockedModel
         * @description `POST /api/project/order` 422 body — the "this is not an order" result.
         *
         *     Fail-closed is a CONTRACT, not a message: the findings ride as reg_meta's own
         *     frozen ``OrderFinding`` models (embedded directly, like every other reg_meta
         *     shape here), each carrying its stable ``code``, its message, and the optional
         *     ``source`` / ``variable`` / ``period`` coordinates that say WHERE — so the SPA
         *     renders them through the same per-finding path as a validation issue, and any
         *     other client can act on them, instead of parsing one flattened string.
         *
         *     ``detail`` is the same flattened one-liner ``order.blocked_message`` gives the
         *     CLI, kept because every 4xx on this API carries a ``detail`` string (FastAPI's
         *     ``HTTPException`` shape) and generic error handling reads it. ``findings`` is
         *     EMPTY when the spec never reached the materializer (a structurally invalid
         *     project — the gate's own 422), which is exactly the truth: nothing found it
         *     unorderable, it was never ordered.
         */
        OrderBlockedModel: {
            /** Detail */
            detail: string;
            /** Findings */
            findings: components["schemas"]["OrderFinding"][];
        };
        /**
         * OrderEntry
         * @description One resolved logical→physical binding of the order.
         *
         *     `source` is the project source name, so an entry stays traceable to the
         *     binding that produced it. `requested_period` is the AVAILABILITY-CLIPPED
         *     period this table serves (canonically rendered), not the source's raw
         *     declared period — the table itself is ordered whole regardless.
         */
        OrderEntry: {
            logical: components["schemas"]["LogicalCoordinate"];
            physical: components["schemas"]["PhysicalCoordinate"];
            /** Requested Period */
            requested_period: string;
            /** Source */
            source: string;
        };
        /**
         * OrderFinding
         * @description One blocking reason the order cannot be materialized.
         *
         *     Codes: `steward_mismatch`, `project_empty`, `period_not_orderable`,
         *     `variable_unresolved`, `binding_unavailable`, `representation_unknown`,
         *     `representation_unresolved`, `representation_ambiguous`, `mapping_missing`,
         *     `column_window_unavailable`, `coverage_gap`. `period` carries the EXACT offending
         *     subperiod for the coverage codes, so a researcher can fix the request in one
         *     edit.
         */
        OrderFinding: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Period */
            period?: string | null;
            /** Source */
            source?: string | null;
            /** Variable */
            variable?: string | null;
        };
        /**
         * OrderManifest
         * @description The versioned JSON order manifest — machine-written here, machine-read by
         *     the steward-side extract system, never hand-edited.
         */
        OrderManifest: {
            /** Clips */
            clips: components["schemas"]["ClipReport"][];
            /** Entries */
            entries: components["schemas"]["OrderEntry"][];
            provenance: components["schemas"]["OrderProvenance"];
            /**
             * Version
             * @constant
             */
            version: 1;
        };
        /**
         * OrderProvenance
         * @description Everything the steward-side extract system needs to know WHICH project,
         *     against WHICH catalog, for WHICH deployment — so the manifest is
         *     self-contained offline (no network, no catalog lookup at extract time).
         *
         *     `project_hash` is the SHA-256 of the project's canonical JSON, so a manifest
         *     can be tied back to the exact uploaded project bytes.
         *
         *     `mode` names what GROUNDED the entries — a steward's compiled holdings or
         *     the global fallback (canonical resolution alone, blank `table`) — so a
         *     reader never has to infer it from the entry shape.
         */
        OrderProvenance: {
            /**
             * Artifact Kind
             * @enum {string}
             */
            artifact_kind: "catalog" | "steward";
            /** Catalog Generation Id */
            catalog_generation_id: string;
            /** Catalog Schema Version */
            catalog_schema_version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "steward_holdings" | "global_fallback";
            /** Project Hash */
            project_hash: string;
            /** Project Name */
            project_name: string;
            /** Project Reg Meta Version */
            project_reg_meta_version: string;
            /** Project Schema Version */
            project_schema_version: string;
            /** Steward */
            steward: string;
        };
        /**
         * Panel
         * @description A panel definition over sources.
         *
         *     Members are stored uniformly as ``PanelMember``. The bare-string
         *     shorthand (a source name with panel-level key defaults) is normalized
         *     to ``PanelMember(source=<name>)`` by the ``members`` validator, so
         *     consumers never branch on ``str | PanelMember``. Source-collision (each
         *     source belongs to at most one panel) and composite ordering /
         *     homogeneity rules are enforced by the structural validator, not here.
         */
        Panel: {
            /**
             * Comment
             * @default null
             */
            comment: string | null;
            /**
             * Entity Key
             * @default null
             */
            entity_key: string | string[] | null;
            /** Members */
            members: (string | components["schemas"]["PanelMember"])[];
            /** Panel Id */
            panel_id: string;
            /**
             * Time Key
             * @default null
             */
            time_key: number | string | components["schemas"]["LiteralPeriod"] | components["schemas"]["TimeRange"] | (number | string | components["schemas"]["LiteralPeriod"] | components["schemas"]["TimeRange"])[] | null;
        };
        /**
         * PanelMember
         * @description A member of a Panel.
         *
         *     ``source`` is the source ``name`` (the panel layer joins on
         *     delivered-data column headers, not FQIDs). ``entity_key`` /
         *     ``time_key`` override panel-level defaults; when both panel and member
         *     leave a key unset, it is inherited from the member's variant's
         *     ``panel_template`` at kit/bundle-build time — the structural
         *     validator does not flag the absence (it has no reg_meta).
         */
        PanelMember: {
            /**
             * Entity Key
             * @default null
             */
            entity_key: string | string[] | null;
            /** Source */
            source: string;
            /**
             * Time Key
             * @default null
             */
            time_key: number | string | components["schemas"]["LiteralPeriod"] | components["schemas"]["TimeRange"] | (number | string | components["schemas"]["LiteralPeriod"] | components["schemas"]["TimeRange"])[] | null;
        };
        /**
         * PeriodRange
         * @description The ``{"from": ..., "to": ...}`` range form of ``Source.period``.
         *
         *     Endpoints follow the same int / period-token-string forms as a bare
         *     period. ``from`` is a Python keyword, so the field is ``from_`` with a
         *     ``"from"`` alias; ``populate_by_name`` lets callers use either.
         *
         *     This bare object is **only** legal as a ``Source.period`` value; a
         *     ``TimePoint`` range uses the discriminated ``TimeRange`` wrapper
         *     (``{"range": {...}}``) so ``TimeKey``'s union stays unambiguous.
         *
         *     ``serialize_by_alias=True`` so ``model_dump()`` emits ``"from"`` (not the
         *     Python-safe ``"from_"``) without every caller having to pass
         *     ``by_alias=True`` — the un-aliased key would fail re-validation
         *     (``_is_period_range_obj`` requires exactly ``{"from", "to"}``).
         */
        PeriodRange: {
            /** From */
            from: number | string;
            /** To */
            to: number | string;
        };
        /**
         * PhysicalCoordinate
         * @description What the steward delivers: the entry's physical coordinate.
         *
         *     `table` is the inventory's opaque exact identifier (a delivery filename or a
         *     schema-qualified SQL table), `column` its literal case-preserving physical
         *     column, and `edition` the table's curated edition rendered canonically (a
         *     period token, an explicit `lo..hi` range, or a comma-joined list for an
         *     interrupted series).
         *
         *     `partition` is the table's disjoint-partition label when it carries one
         *     — the shard of the edition's population this table delivers — so the
         *     extractor can see it; it is absent from the JSON otherwise. Extraction
         *     preserves delivery topology: what goes in as two partitions comes out as two
         *     files, distinguished by the partition token `extraction_filenames` adds.
         *
         *     In the global-deployment fallback there is no physical topology: `table`
         *     is blank, `column` carries the resolved canonical column, `edition` equals
         *     the entry's requested period, and there is no partition.
         */
        PhysicalCoordinate: {
            /** Column */
            column: string;
            /** Edition */
            edition: string;
            /** Partition */
            partition?: string | null;
            /** Table */
            table: string;
        };
        /**
         * ProjectData
         * @description The top-level ``project_data.json`` shape.
         *
         *     The root is closed like every nested ``_Model``: an unknown field is a
         *     model-construction error. API boundaries still run the accumulating
         *     structural validator first so callers receive one stable
         *     ``unexpected_field`` issue per unknown key rather than a fail-fast Pydantic
         *     error. A future extension needs an explicit modeled container; arbitrary
         *     namespaced root blocks are not part of the v1 contract.
         */
        ProjectData: {
            /** Name */
            name: string;
            /**
             * Panels
             * @default []
             */
            panels: components["schemas"]["Panel"][];
            /** Reg Meta Version */
            reg_meta_version: string;
            /** Schema Version */
            schema_version: string;
            /** Sources */
            sources: components["schemas"]["Source"][];
            /**
             * Steward
             * @enum {string}
             */
            steward: "global" | "ifau" | "swecov";
            /** @default null */
            window: components["schemas"]["StudyWindow"] | null;
        };
        /**
         * Source
         * @description A data source / table in the spec.
         *
         *     ``register_variant`` is the 3-part variant **coordinate**
         *     (``<provider>/<register>/<variant>``) — not an FQID kind (see reg_meta/DESIGN.md → FQID grammar), but
         *     the same 3-part grammar. ``period`` is always required and polymorphic
         *     (``Period``). Together ``(register_variant's variant, period)`` selects
         *     each binding variable's ``variable_state``. ``name`` is the internal
         *     source handle referenced by panel members; it is not an FQID.
         */
        Source: {
            /** Bindings */
            bindings: components["schemas"]["Binding"][];
            /** Name */
            name: string;
            /** Period */
            period: number | string | components["schemas"]["PeriodRange"] | (number | string | components["schemas"]["PeriodRange"])[];
            /** Register Variant */
            register_variant: string;
        };
        /**
         * StudyWindow
         * @description The optional ``{"from": <year>, "to": <year>}`` project study window.
         *
         *     The global "project window" the redesigned subject page defaults each
         *     page's period picker to (see issue #611 → Period model). Deliberately
         *     NOT the full ``Period`` / ``PeriodRange`` grammar: it is a plain
         *     year-int pair, matching the year-granular header slider. Per-page
         *     deviation (months/quarters/terms, interrupted segments) keeps the rich
         *     grammar via ``?period``; this window only seeds the default.
         *
         *     ``from`` is a Python keyword, so the field is ``from_`` with a ``"from"``
         *     alias — mirroring ``PeriodRange``. ``serialize_by_alias=True`` so
         *     ``model_dump()`` emits ``"from"`` (not ``"from_"``) without callers
         *     passing ``by_alias=True``.
         *
         *     Endpoints are plain ``int`` years (not the ``int | str`` period-token
         *     forms of ``PeriodRange``): the window is year-granular by design. The
         *     only invariant is ``to >= from`` — a same-year window (``from == to``)
         *     is valid; a window can't end before it starts.
         */
        StudyWindow: {
            /** From */
            from: number;
            /** To */
            to: number;
        };
        /**
         * TimeRange
         * @description The ``{"range": {"from": ..., "to": ...}}`` time_key form.
         *
         *     The discriminated wrapper for a period range in ``TimeKey`` position —
         *     distinct from the bare ``{"from", "to"}`` object, which is legal only
         *     as a ``Source.period`` (``PeriodRange``). The wrapper keeps the
         *     ``TimePoint`` union unambiguous.
         */
        TimeRange: {
            range: components["schemas"]["PeriodRange"];
        };
        /**
         * ValidationIssueModel
         * @description One validation issue — a 1:1 Pydantic wrapper of reg_schema's frozen
         *     ``ValidationIssue`` dataclass. ``level`` is the tri-state severity; ``path`` is
         *     an RFC-6901 JSON pointer into ``project_data.json`` (empty for whole-document
         *     issues); ``code`` is the stable, namespaced rule identifier the SPA maps to a
         *     UI affordance.
         */
        ValidationIssueModel: {
            /** Code */
            code: string;
            /**
             * Level
             * @enum {string}
             */
            level: "error" | "warning" | "info";
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Successor Fqid */
            successor_fqid?: string | null;
        };
        /**
         * ValidationResultModel
         * @description `POST /api/project/validate` response — the concatenated issue list
         *     (structural ⧺ semantic) plus the derived ``ok`` flag. The body is reg_meta's
         *     ``semantic.validation_json`` verbatim; this model types it for OpenAPI.
         *
         *     ``ok`` mirrors ``reg_schema.ValidationResult.ok``: True iff NO error-level
         *     issue is present (warnings/info do not flip it). A validation FAILURE is a
         *     SUCCESSFUL validation RESPONSE — this carries HTTP 200 with ``ok=false`` and
         *     the issues; 4xx is reserved for a malformed request (bad JSON / oversized body
         *     / wrong content-type), never for a spec that simply failed to validate.
         */
        ValidationResultModel: {
            /** Issues */
            issues: components["schemas"]["ValidationIssueModel"][];
            /** Ok */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    order_project_api_project_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderManifest"];
                };
            };
            /** @description Not an order: the spec is invalid, or the materializer fail-closed on it. Carries the typed findings. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderBlockedModel"];
                };
            };
        };
    };
    validate_project_api_project_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResultModel"];
                };
            };
        };
    };
}
