/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The catalog's branding, identity and headline counts, for the SPA. */
        get: operations["context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search the catalog's registers, variables, classifications and codes in one ranked list. `q` is free text; `type` keeps one kind of hit; `register` (a FQID or a bare name) and `period` (2019, 2015..2019, LA2019, 2019-03) filter; pass `next_cursor` back as `cursor` for the next page. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description `shape.Context`: branding, artifact identity and headline counts for the SPA. */
        Context: {
            import_date: string;
            period_span?: components["schemas"]["PeriodSpan"] | null;
            reg_meta_version: string;
            schema_version: string;
            sizes: components["schemas"]["Sizes"];
            steward: components["schemas"]["Steward"];
        };
        /** @description The error document `{code, class, message, remediation, fields}` (section 7). */
        Error: {
            class: string;
            code: string;
            fields: Record<string, never>;
            message: string;
            remediation: string;
        };
        GroupMember: {
            delivery_column?: string | null;
            fqid: string;
            name?: string | null;
        };
        /** @description The response `meta` (`shape.Meta`). */
        Meta: {
            contract_version: string;
            generation: string;
            scope: components["schemas"]["Scope"];
        };
        /** @description The first and last year of the steward's held periods. */
        PeriodSpan: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
        };
        /**
         * @description The read scope (section 7); every read takes it.
         * @enum {string}
         */
        Scope: "holdings" | "reference";
        /** @description `shape.SearchHit`, of the types the variable arm returns. */
        SearchHit: {
            definition?: string | null;
            delivery_column_names: string[];
            fqid?: string | null;
            name?: string | null;
            operational_definition?: string | null;
            register_name?: string | null;
            /** @enum {string} */
            type: "variable";
        } | {
            key: string;
            kind: string;
            label: string;
            matched_count: number;
            members: components["schemas"]["GroupMember"][];
            register_name?: string | null;
            /** @enum {string} */
            type: "group";
        };
        /** @description `Page<SearchHit>`. */
        SearchPage: {
            items: components["schemas"]["SearchHit"][];
            next_cursor?: string | null;
        };
        /** @description Browse-addressable (slugged) providers, registers and variables in the scope. */
        Sizes: {
            /** Format: int64 */
            providers: number;
            /** Format: int64 */
            registers: number;
            /** Format: int64 */
            variables: number;
        };
        /** @description Deployment branding, `reg_webapp/stewards/<catalog>/steward.json`. */
        Steward: {
            id: string;
            long_name: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    context: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Context"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                type?: "register" | "variable" | "classification" | "classification_code" | "register_value";
                register?: string;
                period?: string;
                scope?: components["schemas"]["Scope"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SearchPage"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
}
