/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The catalog's branding, identity and headline counts, for the SPA. */
        get: operations["context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/doc/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One documentation entry by variable name or filename (with or without `.md`): its register, tags and source, a 500-character `excerpt` and the full markdown `body`. */
        get: operations["docs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/file/{ref}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A related document's bytes, served inline. */
        get: {
            parameters: {
                query?: {
                    scope?: components["schemas"]["Scope"];
                };
                header?: never;
                path: {
                    ref: string;
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The raw bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": unknown;
                    };
                };
                /** @description An error in `api/errors.toml` */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["Error"];
                            meta: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/related/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A register's related documents (rehosted PDFs): title, source, license, and the `sha256` and `byte_size` of the bytes `/api/docs/file/{ref}/{filename}` serves. `ref` is a register FQID or a bare name. */
        get: operations["docs_related"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search the catalog's registers, variables, classifications and codes in one ranked list. `q` is free text; `type` keeps one kind of hit; `register` (a FQID or a bare name) and `period` (2019, 2015..2019, LA2019, 2019-03) filter; pass `next_cursor` back as `cursor` for the next page. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CodeClassification: {
            fqid?: string | null;
            name?: string | null;
            short_name?: string | null;
        };
        CodeVariable: {
            fqid?: string | null;
            name?: string | null;
            register_name?: string | null;
        };
        /** @description `shape.Context`: branding, artifact identity and headline counts for the SPA. */
        Context: {
            import_date: string;
            period_span?: components["schemas"]["PeriodSpan"] | null;
            reg_meta_version: string;
            schema_version: string;
            sizes: components["schemas"]["Sizes"];
            steward: components["schemas"]["Steward"];
        };
        /** @description A documentation entry: its metadata, a preview and the full markdown. */
        DocDetail: {
            /** @description The full markdown, for agents. */
            body: string;
            display_name: string;
            /** @description The plain text's first 500 characters, for the SPA. */
            excerpt?: string | null;
            filename: string;
            register: string;
            source?: string | null;
            source_title?: string | null;
            source_url?: string | null;
            tags: string[];
            variable?: string | null;
        };
        Edition: {
            /** Format: int64 */
            effective_year?: number | null;
            fqid?: string | null;
            name?: string | null;
            slug: string;
        };
        /** @description The error document `{code, class, message, remediation, fields}` (section 7). */
        Error: {
            class: string;
            code: string;
            fields: Record<string, never>;
            message: string;
            remediation: string;
        };
        GroupMember: {
            delivery_column?: string | null;
            fqid: string;
            name?: string | null;
        };
        /** @description The response `meta` (`shape.Meta`). */
        Meta: {
            contract_version: string;
            generation: string;
            scope: components["schemas"]["Scope"];
        };
        /** @description The first and last year of the steward's held periods. */
        PeriodSpan: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
        };
        /** @description A related document's metadata; the download route serves its bytes. */
        RelatedDocument: {
            /** Format: int64 */
            byte_size: number;
            fetched: string;
            filename: string;
            license: string;
            sha256: string;
            source_url: string;
            title: string;
        };
        /**
         * @description The read scope (section 7); every read takes it.
         * @enum {string}
         */
        Scope: "holdings" | "reference";
        /** @description `shape.SearchHit`. */
        SearchHit: {
            fqid?: string | null;
            name?: string | null;
            purpose?: string | null;
            /** @enum {string} */
            type: "register";
        } | {
            definition?: string | null;
            delivery_column_names: string[];
            fqid?: string | null;
            name?: string | null;
            operational_definition?: string | null;
            register_name?: string | null;
            /** @enum {string} */
            type: "variable";
        } | {
            key: string;
            kind: string;
            label: string;
            matched_count: number;
            members: components["schemas"]["GroupMember"][];
            register_name?: string | null;
            /** @enum {string} */
            type: "group";
        } | {
            fqid?: string | null;
            name?: string | null;
            short_name?: string | null;
            terminal_fqid?: string | null;
            /** @enum {string} */
            type: "classification";
        } | {
            editions: components["schemas"]["Edition"][];
            fqid?: string | null;
            matched_count: number;
            name?: string | null;
            short_name?: string | null;
            /** @enum {string} */
            type: "classification_succession";
        } | {
            /** Format: int64 */
            classification_count: number;
            classifications: components["schemas"]["CodeClassification"][];
            code: string;
            code_system?: string | null;
            label: string;
            /** @enum {string} */
            type: "code";
            /** Format: int64 */
            variable_count: number;
            variables: components["schemas"]["CodeVariable"][];
        };
        /** @description `Page<SearchHit>`. */
        SearchPage: {
            items: components["schemas"]["SearchHit"][];
            next_cursor?: string | null;
        };
        /** @description Browse-addressable (slugged) providers, registers and variables in the scope. */
        Sizes: {
            /** Format: int64 */
            providers: number;
            /** Format: int64 */
            registers: number;
            /** Format: int64 */
            variables: number;
        };
        /** @description Deployment branding, `reg_webapp/stewards/<catalog>/steward.json`. */
        Steward: {
            id: string;
            long_name: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    context: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Context"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    docs_get: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocDetail"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    docs_related: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RelatedDocument"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                type?: "register" | "variable" | "classification" | "classification_code" | "register_value";
                register?: string;
                period?: string;
                scope?: components["schemas"]["Scope"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SearchPage"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
}
