/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The summary of any ref, by `kind`: a provider, register, variable, classification, `class` (every classification) or a group (`group/<provider>/<register>/<key>`, `group/class/<key>`); no ref is the catalog root. A register lists its variables, groups and variants; a classification its owning variables. `ref` is a FQID or a bare name; a retired FQID answers for its successor, under the successor's `fqid`. */
        get: operations["show_without_ref"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The summary of any ref, by `kind`: a provider, register, variable, classification, `class` (every classification) or a group (`group/<provider>/<register>/<key>`, `group/class/<key>`); no ref is the catalog root. A register lists its variables, groups and variants; a classification its owning variables. `ref` is a FQID or a bare name; a retired FQID answers for its successor, under the successor's `fqid`. */
        get: operations["show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The catalog's branding, identity and headline counts, for the SPA. */
        get: operations["context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/doc/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One documentation entry by variable name or filename (with or without `.md`): its register, tags and source, a 500-character `excerpt` and the full markdown `body`. */
        get: operations["docs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/file/{ref}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A related document's bytes, served inline. */
        get: {
            parameters: {
                query?: {
                    scope?: components["schemas"]["Scope"];
                };
                header?: never;
                path: {
                    ref: string;
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The raw bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": unknown;
                    };
                };
                /** @description An error in `api/errors.toml` */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["Error"];
                            meta: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/related/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A register's related documents (rehosted PDFs): title, source, license, and the `sha256` and `byte_size` of the bytes `/api/docs/file/{ref}/{filename}` serves. `ref` is a register FQID or a bare name. */
        get: operations["docs_related"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search the catalog's registers, variables, classifications and codes in one ranked list. `q` is free text; `type` keeps one kind of hit; `register` (a FQID or a bare name) and `period` (2019, 2015..2019, LA2019, 2019-03) filter; pass `next_cursor` back as `cursor` for the next page. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/states/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A variable's states: each representation it was delivered in, with its variant, bounds, column, coding and the ids of the data warnings that apply to it. Without `period`, the whole history; with `period`, the dated states overlapping it, a state's alias windows standing in for it where they overlap. `variant` and `value_set_version` (`_none` for the empty label) narrow the list. In holdings scope, only what is held, clipped to the held periods. `ref` is a variable FQID or a bare name. */
        get: operations["states"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warnings/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A register's or variable's data warnings, ordered by id: a variable's include its register's unassigned ones. `period`, `variant` and `representation` (a delivery column) keep the warnings that may apply to them; `unassigned_only` keeps the register's unassigned ones. In holdings scope, a variable's warnings apply only to what is held. */
        get: operations["warnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Axis: {
            label: string;
            name: string;
        };
        /** @description A classification edition. Its codes are `values`, its edition chain `graph`. */
        Classification: {
            derivatives: components["schemas"]["Derivation"][];
            derived_from: components["schemas"]["Derivation"][];
            /** @description The classification groups it belongs to. */
            dimensions: components["schemas"]["Group"][];
            family?: components["schemas"]["Family"] | null;
            fqid: string;
            name?: string | null;
            short_name?: string | null;
            /**
             * @description The variables in scope with a state coded by it (today's `get classification
             *     --variables`), unpaged.
             */
            variables: components["schemas"]["OwningVariable"][];
        };
        ClassificationChild: {
            fqid: string;
            name?: string | null;
            short_name?: string | null;
        };
        /** @description A curated group of classifications. */
        ClassificationGroup: {
            axes: components["schemas"]["Axis"][];
            fqid: string;
            key: string;
            label: string;
            members: components["schemas"]["Member"][];
            source: string;
        };
        /**
         * @description Every current classification, with the classification groups and families.
         *     Editions a family stands for are reached through it.
         */
        ClassificationRoot: {
            children: components["schemas"]["ClassificationChild"][];
            families: components["schemas"]["Family"][];
            fqid: string;
            groups: components["schemas"]["Group"][];
            name: string;
        };
        CodeClassification: {
            fqid?: string | null;
            name?: string | null;
            short_name?: string | null;
        };
        CodeVariable: {
            fqid?: string | null;
            name?: string | null;
            register_name?: string | null;
        };
        /** @description A register's concept group: its members in scope. */
        ConceptGroup: {
            axes: components["schemas"]["Axis"][];
            fqid: string;
            key: string;
            label: string;
            members: components["schemas"]["Member"][];
            /** @description The register's FQID. */
            register: string;
            source: string;
            tags: components["schemas"]["Tag"][];
        };
        /**
         * @description The delivered domain against its declared classification; the mismatching codes
         *     are `values`' `nonstandard` and `sentinels` partitions.
         */
        Conformance: {
            /** Format: int64 */
            checked_code_count: number;
            declared_classification_name: string;
            declared_classification_short_name: string;
            declared_classification_slug: string;
            /** Format: int64 */
            matched_code_count: number;
            /** Format: int64 */
            nonconforming_code_count: number;
            /** @description Always empty here (today's light hydration). */
            nonconforming_codes: unknown[];
            /** Format: int64 */
            nonstandard_code_count: number;
            /** Format: double */
            overlap: number;
            /** Format: int64 */
            sentinel_code_count: number;
            status: string;
        };
        /** @description `shape.Context`: branding, artifact identity and headline counts for the SPA. */
        Context: {
            import_date: string;
            period_span?: components["schemas"]["PeriodSpan"] | null;
            reg_meta_version: string;
            schema_version: string;
            sizes: components["schemas"]["Sizes"];
            steward: components["schemas"]["Steward"];
        };
        /**
         * @description The span a variable or column is delivered over: its earliest start and latest
         *     finite end (null when unknown, or when `open_ended`), and the states (held
         *     periods in holdings) behind it.
         */
        Coverage: {
            coverage_from?: string | null;
            coverage_to?: string | null;
            open_ended: boolean;
            /** Format: int64 */
            state_count: number;
        };
        /**
         * @description A retained source limitation or interpretation assumption: today's
         *     `DataWarning`, as the build stored it.
         */
        DataWarning: {
            acknowledged_by?: string | null;
            case_id?: string | null;
            code: string;
            delivery_column_name?: string | null;
            detail: string;
            diagnostic_detail_sha256: string;
            fields: string[];
            refs: components["schemas"]["SourceRecordRef"][];
            register_fqid: string;
            /** @description `warning` or `error`. */
            severity: string;
            source_subject: string;
            summary: string;
            valid_from?: string | null;
            valid_to?: string | null;
            variable_fqid?: string | null;
            variant?: string | null;
            /** @description SHA-256 of the rest of the warning. */
            warning_id: string;
            withheld_output: string[];
        };
        /**
         * @description One `(variant, delivery column)` a variable is delivered under, with its disjoint
         *     windows by start and their span. `column` is null for a state SCB named no
         *     column for.
         */
        Delivery: {
            column?: string | null;
            coverage: components["schemas"]["Coverage"];
            /** @description `intervals`, or `year_independent` (no windows). */
            period_scope: string;
            variant: string;
            windows: components["schemas"]["Window"][];
        };
        /** @description A non-temporal derivation link between classifications. */
        Derivation: {
            fqid?: string | null;
            name?: string | null;
            note?: string | null;
            short_name?: string | null;
        };
        /** @description A documentation entry: its metadata, a preview and the full markdown. */
        DocDetail: {
            /** @description The full markdown, for agents. */
            body: string;
            display_name: string;
            /** @description The plain text's first 500 characters, for the SPA. */
            excerpt?: string | null;
            filename: string;
            register: string;
            source?: string | null;
            source_title?: string | null;
            source_url?: string | null;
            tags: string[];
            variable?: string | null;
        };
        Edition: {
            /** Format: int64 */
            effective_year?: number | null;
            fqid?: string | null;
            name?: string | null;
            slug: string;
        };
        /** @description The error document `{code, class, message, remediation, fields}` (section 7). */
        Error: {
            class: string;
            code: string;
            fields: Record<string, never>;
            message: string;
            remediation: string;
        };
        Facet: {
            axis?: string | null;
            label: string;
            value: string;
        };
        /** @description A one-dimensional classification succession family (ICD, LKF, SNI, SSYK). */
        Family: {
            fqid: string;
            key: string;
            label: string;
        };
        /** @description A group as listed by its register, classification root or member classification. */
        Group: {
            axes: components["schemas"]["Axis"][];
            fqid: string;
            key: string;
            label: string;
            members: components["schemas"]["Member"][];
            source: string;
            tags: components["schemas"]["Tag"][];
        };
        GroupMember: {
            delivery_column?: string | null;
            fqid: string;
            name?: string | null;
        };
        IntegerRange: {
            /** Format: int64 */
            max: number;
            /** Format: int64 */
            min: number;
        };
        /** @description A group member; two members of one variable differ by `delivery_column`. */
        Member: {
            coverage?: components["schemas"]["Coverage"] | null;
            delivery_column?: string | null;
            facets: components["schemas"]["Facet"][];
            fqid: string;
            name?: string | null;
        };
        /** @description The response `meta` (`shape.Meta`). */
        Meta: {
            contract_version: string;
            generation: string;
            scope: components["schemas"]["Scope"];
        };
        ObjectType: {
            definition?: string | null;
            name: string;
        };
        OwningVariable: {
            fqid?: string | null;
            name?: string | null;
            register_name?: string | null;
        };
        /** @description A panel key: a variable slug (or `period`), or several (a composite key). */
        PanelKey: string | string[];
        /** @description The first and last year of the steward's held periods. */
        PeriodSpan: {
            /** Format: int64 */
            from: number;
            /** Format: int64 */
            to: number;
        };
        Population: {
            comment?: string | null;
            date_range?: string | null;
            definition?: string | null;
            name: string;
        };
        /** @description A provider and its registers in scope. */
        Provider: {
            children: components["schemas"]["RegisterChild"][];
            fqid: string;
            name?: string | null;
        };
        /** @description A register: its variables, concept groups and variants in scope. */
        Register: {
            children: components["schemas"]["VariableChild"][];
            fqid: string;
            groups: components["schemas"]["Group"][];
            name?: string | null;
            purpose?: string | null;
            tags: components["schemas"]["Tag"][];
            variants: components["schemas"]["Variant"][];
        };
        RegisterChild: {
            coverage?: components["schemas"]["RegisterCoverage"] | null;
            fqid: string;
            name?: string | null;
            purpose?: string | null;
            tags: components["schemas"]["Tag"][];
        };
        /** @description A register's span: its variables and the earliest and latest of their states. */
        RegisterCoverage: {
            coverage_from?: string | null;
            coverage_to?: string | null;
            open_ended: boolean;
            /** Format: int64 */
            variable_count: number;
        };
        /** @description A related document's metadata; the download route serves its bytes. */
        RelatedDocument: {
            /** Format: int64 */
            byte_size: number;
            fetched: string;
            filename: string;
            license: string;
            sha256: string;
            source_url: string;
            title: string;
        };
        /** @description The catalog root: the providers in scope and the classification root. */
        Root: {
            children: components["schemas"]["RootChild"][];
        };
        RootChild: {
            fqid: string;
            /** @enum {string} */
            kind: "provider";
            name?: string | null;
        } | {
            fqid: string;
            /** @enum {string} */
            kind: "classification_root";
            name: string;
        };
        /**
         * @description The read scope (section 7); every read takes it.
         * @enum {string}
         */
        Scope: "holdings" | "reference";
        /** @description `shape.SearchHit`. */
        SearchHit: {
            fqid?: string | null;
            name?: string | null;
            purpose?: string | null;
            /** @enum {string} */
            type: "register";
        } | {
            definition?: string | null;
            delivery_column_names: string[];
            fqid?: string | null;
            name?: string | null;
            operational_definition?: string | null;
            register_name?: string | null;
            /** @enum {string} */
            type: "variable";
        } | {
            key: string;
            kind: string;
            label: string;
            matched_count: number;
            members: components["schemas"]["GroupMember"][];
            register_name?: string | null;
            /** @enum {string} */
            type: "group";
        } | {
            fqid?: string | null;
            name?: string | null;
            short_name?: string | null;
            terminal_fqid?: string | null;
            /** @enum {string} */
            type: "classification";
        } | {
            editions: components["schemas"]["Edition"][];
            fqid?: string | null;
            matched_count: number;
            name?: string | null;
            short_name?: string | null;
            /** @enum {string} */
            type: "classification_succession";
        } | {
            /** Format: int64 */
            classification_count: number;
            classifications: components["schemas"]["CodeClassification"][];
            code: string;
            code_system?: string | null;
            label: string;
            /** @enum {string} */
            type: "code";
            /** Format: int64 */
            variable_count: number;
            variables: components["schemas"]["CodeVariable"][];
        };
        /** @description `Page<SearchHit>`. */
        SearchPage: {
            items: components["schemas"]["SearchHit"][];
            next_cursor?: string | null;
        };
        /** @description A `kind`-tagged summary of a ref. */
        Show: (components["schemas"]["Root"] & {
            /** @enum {string} */
            kind: "root";
        }) | (components["schemas"]["Provider"] & {
            /** @enum {string} */
            kind: "provider";
        }) | (components["schemas"]["Register"] & {
            /** @enum {string} */
            kind: "register";
        }) | (components["schemas"]["Variable"] & {
            /** @enum {string} */
            kind: "variable";
        }) | (components["schemas"]["ClassificationRoot"] & {
            /** @enum {string} */
            kind: "classification_root";
        }) | (components["schemas"]["Classification"] & {
            /** @enum {string} */
            kind: "classification";
        }) | (components["schemas"]["ConceptGroup"] & {
            /** @enum {string} */
            kind: "concept_group";
        }) | (components["schemas"]["ClassificationGroup"] & {
            /** @enum {string} */
            kind: "classification_group";
        }) | (components["schemas"]["Family"] & {
            /** @enum {string} */
            kind: "classification_family";
        });
        /** @description Browse-addressable (slugged) providers, registers and variables in the scope. */
        Sizes: {
            /** Format: int64 */
            providers: number;
            /** Format: int64 */
            registers: number;
            /** Format: int64 */
            variables: number;
        };
        /** @description One semantic source member a warning cites. */
        SourceRecordRef: {
            semantic_record_key: string[];
            source: string;
        };
        /**
         * @description A state: today's `VariableState` under the catalog page's light hydration (its
         *     codes are the `values` facet).
         */
        State: {
            classifications: components["schemas"]["StateClassification"][];
            /** @description The coding window's start, for a column coded on its own. */
            coding_window_from?: string | null;
            data_length?: string | null;
            data_type?: string | null;
            definition?: string | null;
            delivery_column_name?: string | null;
            description?: string | null;
            is_identifier: boolean;
            measurement_unit?: string | null;
            name?: string | null;
            operational_definition?: string | null;
            /** @description `intervals` or `year_independent`. */
            period_scope: string;
            /**
             * @description The coarsest period token of the bounds; `_default` when year-independent,
             *     null when open-ended.
             */
            period_token?: string | null;
            pooled: boolean;
            provenance?: string | null;
            register_variant_id: string;
            source_register_text?: string | null;
            state_id: string;
            valid_from?: string | null;
            valid_to?: string | null;
            /** @description Always null: a state's codes are the `values` facet. */
            value_set?: unknown[] | null;
            value_set_id?: string | null;
            value_set_summary?: components["schemas"]["ValueSetSummary"] | null;
            value_set_version_label: string;
            variant: string;
            variant_family?: string | null;
            variant_family_label?: string | null;
            variant_label?: string | null;
            /** @description The data warnings that apply to this representation at its bounds. */
            warning_ids: string[];
        };
        /** @description A classification linked to a representation, with its stored conformance verdict. */
        StateClassification: {
            conformance?: components["schemas"]["Conformance"] | null;
            name: string;
            provenance?: string | null;
            short_name: string;
            slug: string;
        };
        StatesPage: {
            items: components["schemas"]["State"][];
            next_cursor?: string | null;
        };
        /** @description Deployment branding, `reg_webapp/stewards/<catalog>/steward.json`. */
        Steward: {
            id: string;
            long_name: string;
            name: string;
        };
        /** @description A tag membership: the tag and this member's rank, star and note. */
        Tag: {
            label: string;
            note?: string | null;
            /** Format: int64 */
            rank: number;
            slug: string;
            starred: boolean;
        };
        /**
         * @description `value_set_summary`: a value set's code count and, when its codes are a dense
         *     integer run, its span.
         */
        ValueSetSummary: {
            code_count: number;
            integer_range?: components["schemas"]["IntegerRange"] | null;
        };
        /**
         * @description A variable's shared metadata. Its states, lineage and succession chain are the
         *     `states`, `lineage` and `graph` operations.
         */
        Variable: {
            definition?: string | null;
            deprecated: boolean;
            description?: string | null;
            fqid: string;
            /** @description The ref of the concept group the variable belongs to. */
            group?: string | null;
            is_identifier: boolean;
            is_sensitive: boolean;
            measurement_unit?: string | null;
            name?: string | null;
            operational_definition?: string | null;
            /** @description The FQIDs of the variables curated as the same variable. */
            same_as: string[];
            source_register_text?: string | null;
            tags: components["schemas"]["Tag"][];
        };
        VariableChild: {
            coverage?: components["schemas"]["Coverage"] | null;
            /** @description Every `(variant, column)` the variable is delivered under in scope. */
            deliveries: components["schemas"]["Delivery"][];
            fqid: string;
            name?: string | null;
        };
        /** @description A register variant (the `variant` filter of `states`), with its versions' prose. */
        Variant: {
            description?: string | null;
            display_group?: string | null;
            name?: string | null;
            panel_entity_key?: components["schemas"]["PanelKey"] | null;
            panel_time_grain?: string | null;
            panel_time_key?: components["schemas"]["PanelKey"] | null;
            slug: string;
            /** @description The key of the variant's succession family: its first head. */
            variant_family?: string | null;
            variant_family_label?: string | null;
            versions: components["schemas"]["Version"][];
        };
        Version: {
            description?: string | null;
            measurement_information?: string | null;
            name?: string | null;
            object_types: components["schemas"]["ObjectType"][];
            populations: components["schemas"]["Population"][];
        };
        Window: {
            valid_from: string;
            valid_to: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    show_without_ref: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Show"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    show: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Show"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    context: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Context"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    docs_get: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DocDetail"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    docs_related: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RelatedDocument"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                type?: "register" | "variable" | "classification" | "classification_code" | "register_value";
                register?: string;
                period?: string;
                scope?: components["schemas"]["Scope"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SearchPage"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    states: {
        parameters: {
            query?: {
                period?: string;
                variant?: string;
                value_set_version?: string;
                scope?: components["schemas"]["Scope"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StatesPage"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    warnings: {
        parameters: {
            query?: {
                period?: string;
                variant?: string;
                representation?: string;
                unassigned_only?: boolean;
                scope?: components["schemas"]["Scope"];
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DataWarning"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            /** @description An error in `api/errors.toml` */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["Error"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
}
