[[accept]]
register = "sos/dors"
key = "dodsorsak"
axis = "ordinal"

[[accept]]
register = "sos/dors"
key = "substans"
axis = "ordinal"

[[accept]]
register = "sos/dors"
key = "dodsorsak-position"
label = "Position på intyget av dödsorsaken (per dödsorsak)"
axis = "ordinal"

[[accept]]
register = "sos/par"
key = "atgardsdatum"
axis = "ordinal"

[[accept]]
register = "sos/par"
key = "yttre-orsakskod"
axis = "ordinal"

[[accept]]
register = "sos/par"
key = "anestesikod"
axis = "ordinal"

[[accept]]
register = "sos/mfr"
key = "barnets-diagnoskod-bk"
axis = "ordinal"

[[accept]]
register = "sos/hsl"
key = "yrkesbeteckning"
axis = "ordinal"

[[accept]]
register = "sos/lmed"
key = "specialistutbildningskod"
axis = "ordinal"

[[accept]]
register = "sos/mfr"
key = "diagnoskod-barnet"
label = "Diagnoskod, barnet"
axis = "ordinal"

[[accept]]
register = "scb/rtb"
key = "personnrvard"
axis = "ordinal"

[[accept]]
register = "scb/breg"
key = "personnrvard"
axis = "ordinal"

[[accept]]
register = "scb/rtb"
key = "personnrap"
axis = "ordinal"

[[accept]]
register = "scb/breg"
key = "personnrap"
axis = "ordinal"

[[accept]]
register = "scb/flergenreg"
key = "personnrf"
axis = "ordinal"

[[accept]]
register = "sos/mfr"
key = "atgardskod-barnet"
label = "Åtgärdskod, barnet"
axis = "ordinal"

[[accept]]
register = "scb/energianvandning-fiske"
key = "signal"
label = "Fartygets identitetssnummer"
axis = "ordinal"

[[accept]]
register = "sos/mfr"
key = "atgardskod-forlosta"
label = "Åtgärdskod, den förlösta"
axis = "ordinal"

[[accept]]
register = "sos/mfr"
key = "diagnoskod-forlosta"
label = "Diagnoskod, den förlösta"
axis = "ordinal"

[[accept]]
register = "sos/mfr"
key = "diagnoskod-graviditet"
label = "Diagnoskod under graviditet"
axis = "ordinal"
