[classification]
short_name = "LKF1984"
slug = "lkf1984"
name = "Län, kommuner och församlingar 1984"
name_en = "Counties, municipalities and parishes 1984"
publisher = "SCB"
valid_from = 1984
valid_to = 1984
url = "https://www.scb.se/hitta-statistik/regional-statistik-och-kartor/regionala-indelningar/lan-och-kommuner/"
codes_file = "lkf1984.csv"

[binding]
value_set_labels = [
  "LKF 1984-01-01/ Län, kommuner och församlingar",
]
