"""Shared CSV test data for regmeta tests.

Extracted from conftest.py so it can be imported without conftest name collisions
when pytest collects multiple test directories.
"""

from __future__ import annotations

from pathlib import Path

PIPE = "|"

REGISTERINFORMATION_HEADER = PIPE.join(
    [
        "Registernamn",
        "Registerrubrik",
        "Registersyfte",
        "Registervariantrubrik",
        "Registervariantnamn",
        "Registervariantbeskrivning",
        "RegistervariantSekretess",
        "Registerversionnamn",
        "Registerversionbeskrivning",
        "Registerversionmätinformation",
        "Registerversion_DocStaus",
        "Registerversion_ForstaGodkannandeDatum",
        "Registerversion_SenastGodkandDatum",
        "Populationnamn",
        "Populationdefinition",
        "Populationkommentar",
        "Populationdatum",
        "Objekttypnamn",
        "Objekttypdefinition",
        "Variabelnamn",
        "Variabeldefinition",
        "Variabelbeskrivning",
        "VariabelOperationell_definition",
        "VariabelReferenstid",
        "VariabelHämtadFrån",
        "VariabelRegister_Källa",
        "VariabelExtern_kommentar",
        "Mattenhet",
        "Kolumnnamn",
        "Datatyp",
        "Datalängd",
        "CVID",
        "RegisterId",
        "RegVarID",
        "RegVerID",
        "VarId",
    ]
)


def _ri_row(
    regname,
    regtitle,
    purpose,
    variantname,
    varianttitle,
    variantdesc,
    variantsecrecy,
    versionname,
    versiondesc,
    versionmeas,
    docstatus,
    firstdate,
    lastdate,
    popname,
    popdef,
    popcomment,
    popdate,
    objname,
    objdef,
    varname,
    vardef,
    vardesc,
    varopdef,
    varreftime,
    varfrom,
    varsource,
    varcomment,
    unit,
    colname,
    datatype,
    datalen,
    cvid,
    regid,
    regvarid,
    regverid,
    varid,
):
    return PIPE.join(
        [
            regname,
            regtitle,
            purpose,
            varianttitle,
            variantname,
            variantdesc,
            variantsecrecy,
            versionname,
            versiondesc,
            versionmeas,
            docstatus,
            firstdate,
            lastdate,
            popname,
            popdef,
            popcomment,
            popdate,
            objname,
            objdef,
            varname,
            vardef,
            vardesc,
            varopdef,
            varreftime,
            varfrom,
            varsource,
            varcomment,
            unit,
            colname,
            datatype,
            datalen,
            cvid,
            regid,
            regvarid,
            regverid,
            varid,
        ]
    )


REGISTERINFORMATION_ROWS = [
    _ri_row(
        "TESTREG",
        "Testregistret",
        "Testning",
        "Individer",
        "Individer",
        "Alla individer",
        "Nej",
        "2020",
        "Version 2020",
        "",
        "Godkänd",
        "2020-01-01",
        "2020-12-31",
        "Hela befolkningen",
        "Alla personer",
        "",
        "2020-12-31",
        "Person",
        "Fysisk person",
        "Kön",
        "Personens kön",
        "Kön enligt folkbokföring",
        "",
        "",
        "",
        "",
        "",
        "",
        "Kon",
        "int",
        "1",
        "1001",
        "1",
        "10",
        "100",
        "44",
    ),
    _ri_row(
        "TESTREG",
        "Testregistret",
        "Testning",
        "Individer",
        "Individer",
        "Alla individer",
        "Nej",
        "2020",
        "Version 2020",
        "",
        "Godkänd",
        "2020-01-01",
        "2020-12-31",
        "Hela befolkningen",
        "Alla personer",
        "",
        "2020-12-31",
        "Person",
        "Fysisk person",
        "TestVar",
        "En testvariabel",
        "Beskrivning av test",
        "",
        "",
        "",
        "",
        "",
        "",
        "TestCol",
        "varchar",
        "10",
        "1002",
        "1",
        "10",
        "100",
        "100",
    ),
    _ri_row(
        "TESTREG",
        "Testregistret",
        "Testning",
        "Individer",
        "Individer",
        "Alla individer",
        "Nej",
        "2020",
        "Version 2020",
        "",
        "Godkänd",
        "2020-01-01",
        "2020-12-31",
        "Hela befolkningen",
        "Alla personer",
        "",
        "2020-12-31",
        "Person",
        "Fysisk person",
        "TestVar",
        "En testvariabel",
        "Beskrivning av test",
        "",
        "",
        "",
        "",
        "",
        "",
        "TestKolumn",
        "varchar",
        "10",
        "1002",
        "1",
        "10",
        "100",
        "100",
    ),
    _ri_row(
        "TESTREG",
        "Testregistret",
        "Testning",
        "Individer",
        "Individer",
        "Alla individer",
        "Nej",
        "2021",
        "Version 2021",
        "",
        "Godkänd",
        "2021-01-01",
        "2021-12-31",
        "Hela befolkningen",
        "Alla personer",
        "",
        "2021-12-31",
        "Person",
        "Fysisk person",
        "Kön",
        "Personens kön",
        "Kön enligt folkbokföring",
        "",
        "",
        "",
        "",
        "",
        "",
        "Kon",
        "int",
        "1",
        "1003",
        "1",
        "10",
        "101",
        "44",
    ),
    _ri_row(
        "TESTREG",
        "Testregistret",
        "Testning",
        "Individer",
        "Individer",
        "Alla individer",
        "Nej",
        "2022",
        "Version 2022",
        "",
        "Godkänd",
        "2022-01-01",
        "2022-12-31",
        "Hela befolkningen",
        "Alla personer",
        "",
        "2022-12-31",
        "Person",
        "Fysisk person",
        "Kön",
        "Personens kön",
        "Kön enligt folkbokföring",
        "",
        "",
        "",
        "",
        "",
        "",
        "Kon",
        "int",
        "1",
        "1004",
        "1",
        "10",
        "102",
        "44",
    ),
    _ri_row(
        "TESTREG",
        "Testregistret",
        "Testning",
        "Individer",
        "Individer",
        "Alla individer",
        "Nej",
        "2022",
        "Version 2022",
        "",
        "Godkänd",
        "2022-01-01",
        "2022-12-31",
        "Hela befolkningen",
        "Alla personer",
        "",
        "2022-12-31",
        "Person",
        "Fysisk person",
        "ÅÄÖVar",
        "Variabel med svenska tecken",
        "Åäö i beskrivning",
        "",
        "",
        "",
        "",
        "",
        "",
        "AaoCol",
        "varchar",
        "5",
        "1005",
        "1",
        "10",
        "102",
        "200",
    ),
    _ri_row(
        "OTHERREG",
        "Annat register",
        "Annat syfte",
        "Företag",
        "Företag",
        "Alla företag",
        "Ja",
        "2021",
        "Version 2021",
        "",
        "Godkänd",
        "2021-01-01",
        "2021-12-31",
        "Alla företag",
        "Samtliga företag",
        "",
        "2021-12-31",
        "Företag",
        "Juridisk person",
        "Kön",
        "Ägarkön",
        "Kön på ägare",
        "",
        "",
        "Testregistret",
        "TESTREG",
        "",
        "",
        "KON",
        "int",
        "1",
        "2001",
        "2",
        "20",
        "200",
        "44",
    ),
    _ri_row(
        "OTHERREG",
        "Annat register",
        "Annat syfte",
        "Företag",
        "Företag",
        "Alla företag",
        "Ja",
        "2021",
        "Version 2021",
        "",
        "Godkänd",
        "2021-01-01",
        "2021-12-31",
        "Alla företag",
        "Samtliga företag",
        "",
        "2021-12-31",
        "Företag",
        "Juridisk person",
        "UniqueVar",
        "Unik variabel",
        "Bara i reg 2",
        "",
        "",
        "",
        "",
        "",
        "",
        "UniqCol",
        "varchar",
        "20",
        "2002",
        "2",
        "20",
        "200",
        "300",
    ),
    # Variable with parenthesized abbreviation in VariabelRegister_Källa
    _ri_row(
        "OTHERREG",
        "Annat register",
        "Annat syfte",
        "Företag",
        "Företag",
        "Alla företag",
        "Ja",
        "2021",
        "Version 2021",
        "",
        "Godkänd",
        "2021-01-01",
        "2021-12-31",
        "Alla företag",
        "Samtliga företag",
        "",
        "2021-12-31",
        "Företag",
        "Juridisk person",
        "ParenVar",
        "Variabel med parentes-källa",
        "Test av parentesupplösning",
        "",
        "",
        "Testregistret",
        "Testregistret (TESTREG) : Folkbokföringsuppgifter",
        "",
        "",
        "ParenCol",
        "varchar",
        "10",
        "2003",
        "2",
        "20",
        "200",
        "301",
    ),
    # Variable with unresolvable external source (no matching register)
    _ri_row(
        "OTHERREG",
        "Annat register",
        "Annat syfte",
        "Företag",
        "Företag",
        "Alla företag",
        "Ja",
        "2021",
        "Version 2021",
        "",
        "Godkänd",
        "2021-01-01",
        "2021-12-31",
        "Alla företag",
        "Samtliga företag",
        "",
        "2021-12-31",
        "Företag",
        "Juridisk person",
        "ExternVar",
        "Variabel från externt system",
        "Från myndighet utanför MetaPlus",
        "",
        "",
        "Register, ej i MetaPlus",
        "Försäkringskassan",
        "",
        "",
        "ExtCol",
        "varchar",
        "10",
        "2004",
        "2",
        "20",
        "200",
        "302",
    ),
]

UNIKA_HEADER = PIPE.join(
    [
        "Registernamn",
        "Registerrubrik",
        "Registervariantnamn",
        "Registervariantrubrik",
        "Variabelnamn",
        "Kolumnnamn",
        "VersionForsta",
        "VersionSista",
        "KansligVariabel",
        "KansligVariabelIbland",
        "Identitetsvariabel",
    ]
)

UNIKA_ROWS = [
    PIPE.join(
        [
            "TESTREG",
            "Testregistret",
            "Individer",
            "Individer",
            "Kön",
            "Kon",
            "2020",
            "2022",
            "Nej",
            "Nej",
            "Nej",
        ]
    ),
    PIPE.join(
        [
            "TESTREG",
            "Testregistret",
            "Individer",
            "Individer",
            "TestVar",
            "TestCol",
            "2020",
            "2020",
            "Ja",
            "Nej",
            "Nej",
        ]
    ),
    PIPE.join(
        [
            "OTHERREG",
            "Annat register",
            "Företag",
            "Företag",
            "Kön",
            "KON",
            "2021",
            "2021",
            "Nej",
            "Nej",
            "Nej",
        ]
    ),
]

IDENTIFIERARE_HEADER = PIPE.join(["VarID", "Variabelnamn", "Variabeldefinition"])

IDENTIFIERARE_ROWS = [
    PIPE.join(["44", "Kön", "Personens kön"]),
]

TIMESERIES_HEADER = PIPE.join(
    [
        "Namn",
        "Handelse",
        "Beskrivning",
        "Entitet",
        "ID1",
        "ID2",
        "FilID",
    ]
)

TIMESERIES_ROWS = [
    PIPE.join(["TESTREG", "Kodändring", "Kod 3 ändrad", "Variabel", "100", "", "1"]),
]

VARDEMANGDER_HEADER = PIPE.join(
    [
        "Värdemängdsversion",
        "Värdemängdsnivå",
        "Värdekod",
        "Värdebenämning",
        "CVID",
        "ItemId",
    ]
)

VARDEMANGDER_ROWS = [
    PIPE.join(["Kön", "1", "1", "Man", "1001", "5001"]),
    PIPE.join(["Kön", "1", "2", "Kvinna", "1001", "5002"]),
    PIPE.join(["Kön", "1", "1", "Man", "1001", "5003"]),
    PIPE.join(["Kön", "1", "1", "Man", "1003", "5001"]),
    PIPE.join(["Kön", "1", "2", "Kvinna", "1003", "5002"]),
    PIPE.join(["Kön", "1", "1", "Man", "2001", "5001"]),
    PIPE.join(["Kön", "1", "2", "Kvinna", "2001", "5002"]),
    PIPE.join(["Kön", "1", "2", "Kvinna", "2001", ""]),
    PIPE.join(["Unknown", "1", "99", "Phantom", "9999", "5099"]),
]

VALID_DATES_HEADER = PIPE.join(["ItemID", "ValidFrom", "ValidTo"])
VALID_DATES_ROWS = [
    PIPE.join(["5001", "2000-01-01", "2010-12-31"]),
    PIPE.join(["5003", "2015-01-01", "2025-12-31"]),
]


def write_csv(
    path: Path, header: str, rows: list[str], encoding: str = "cp1252"
) -> None:
    content = header + "\r\n" + "\r\n".join(rows) + "\r\n"
    path.write_bytes(content.encode(encoding))
