[[family]]
key = "ssyk"
members = ["ssyk1996", "ssyk2012"]
aliases = [
  "Standard för svensk yrkesklassificering (SSYK)",
  "https://www.scb.se/dokumentation/klassifikationer-och-standarder/standard-for-svensk-yrkesklassificering-ssyk/",
]

[[family]]
key = "agarkat"
members = ["agarkat2000", "agarkat2020"]
